### PR TITLE
remove lodash.clonedeep dependency

### PR DESCRIPTION
**Pull request by kaizhu256**
after this patch, a quick grep show clonedeep / cloneDeep has been removed from non-node_modules code

```
root@localhost:~/src/npm# git grep clonedeep
CHANGELOG.md:  `lodash.clonedeep@4.3.2`
CHANGELOG.md:  `lodash.clonedeep@4.3.1`
CHANGELOG.md:  `lodash.clonedeep@4.3.0`
CHANGELOG.md:  `lodash.clonedeep@4.1.0`
CHANGELOG.md:  `lodash.clonedeep@4.0.4`:
CHANGELOG.md:  `lodash.clonedeep@4.0.2`:
CHANGELOG.md:  `lodash.clonedeep@4.0.1`: Bug fixes, including the non-linear performance
CHANGELOG.md:  `lodash.clonedeep@3.0.2` ([@jdalton](https://github.com/jdalton))
node_modules/lodash.clonedeep/README.md:# lodash.clonedeep v4.3.2
node_modules/lodash.clonedeep/README.md:$ npm i --save lodash.clonedeep
node_modules/lodash.clonedeep/README.md:var cloneDeep = require('lodash.clonedeep');
node_modules/lodash.clonedeep/README.md:See the [documentation](https://lodash.com/docs#cloneDeep) or [package source](https://github.com/lodash/lodash/blob/4.3.2-npm-packages/lodash.clonedeep) for more details.
node_modules/lodash.clonedeep/node_modules/lodash._baseclone/package.json:      "/Users/rebecca/code/npm/node_modules/lodash.clonedeep"
node_modules/lodash.clonedeep/node_modules/lodash._baseclone/package.json:  "_location": "/lodash.clonedeep/lodash._baseclone",
node_modules/lodash.clonedeep/node_modules/lodash._baseclone/package.json:    "/lodash.clonedeep"
node_modules/lodash.clonedeep/node_modules/lodash._baseclone/package.json:  "_where": "/Users/rebecca/code/npm/node_modules/lodash.clonedeep",
node_modules/lodash.clonedeep/package.json:      "lodash.clonedeep@4.3.2",
node_modules/lodash.clonedeep/package.json:  "_from": "lodash.clonedeep@4.3.2",
node_modules/lodash.clonedeep/package.json:  "_id": "lodash.clonedeep@4.3.2",
node_modules/lodash.clonedeep/package.json:  "_location": "/lodash.clonedeep",
node_modules/lodash.clonedeep/package.json:    "tmp": "tmp/lodash.clonedeep-4.3.2.tgz_1459310662712_0.4621682942379266"
node_modules/lodash.clonedeep/package.json:    "name": "lodash.clonedeep",
node_modules/lodash.clonedeep/package.json:    "raw": "lodash.clonedeep@4.3.2",
node_modules/lodash.clonedeep/package.json:  "_resolved": "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.3.2.tgz",
node_modules/lodash.clonedeep/package.json:  "_spec": "lodash.clonedeep@4.3.2",
node_modules/lodash.clonedeep/package.json:    "tarball": "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.3.2.tgz"
node_modules/lodash.clonedeep/package.json:    "clonedeep"
node_modules/lodash.clonedeep/package.json:  "name": "lodash.clonedeep",
root@localhost:~/src/npm# 
root@localhost:~/src/npm# git grep cloneDeep
CHANGELOG.md:  Revert last weeks change to use JSON clone instead of `lodash.cloneDeep`.
CHANGELOG.md:We were also using `lodash`'s `cloneDeep` on `package.json` data which is
CHANGELOG.md:  Use JSON clone instead of `lodash.cloneDeep`.
node_modules/lodash.clonedeep/README.md:The [lodash](https://lodash.com/) method `_.cloneDeep` exported as a [Node.js](https://nodejs.org/) module.
node_modules/lodash.clonedeep/README.md:var cloneDeep = require('lodash.clonedeep');
node_modules/lodash.clonedeep/README.md:See the [documentation](https://lodash.com/docs#cloneDeep) or [package source](https://github.com/lodash/lodash/blob/4.3.2-npm-packages/lodash.clonedeep) for more details.
node_modules/lodash.clonedeep/index.js: * var deep = _.cloneDeep(objects);
node_modules/lodash.clonedeep/index.js:function cloneDeep(value) {
node_modules/lodash.clonedeep/index.js:module.exports = cloneDeep;
node_modules/lodash.clonedeep/node_modules/lodash._baseclone/index.js: * The base implementation of `_.clone` and `_.cloneDeep` which tracks
node_modules/lodash.clonedeep/package.json:  "description": "The lodash method `_.cloneDeep` exported as a module.",
node_modules/request/node_modules/hawk/node_modules/hoek/lib/index.js:    var cloneDeep = false;
node_modules/request/node_modules/hawk/node_modules/hoek/lib/index.js:                cloneDeep = true;
node_modules/request/node_modules/hawk/node_modules/hoek/lib/index.js:        cloneDeep = true;
node_modules/request/node_modules/hawk/node_modules/hoek/lib/index.js:    if (cloneDeep) {
```

### CODE REVIEW

**Comment by KenanY** [comment]
Didn't this cause https://github.com/npm/npm/issues/11349 last time it was merged (https://github.com/npm/npm/pull/11306)?

**Comment by KenanY** [comment]
(specifically I am referring to the change in `lib/fetch-package-metadata.js`)

**Comment by kaizhu256** [comment]
sorry i didn't kno about that issue.  @KenanY i updated lib/fetch-package-metadata.js to handle cicular references

here's a simple test of my simple clone function

```
local.utility2.jsonStringifyOrdered = function (element, replacer, space) {
/*
 * this function will JSON.stringify the element,
 * with object-keys sorted and circular-references removed
 */
  var circularList, stringify, tmp;
  stringify = function (element) {
  /*
   * this function will recursively stringify the element,
   * with object-keys sorted and circular-references removed
   */
    // if element is an object, then recurse with its items, sorted by their keys
    if (element &&
        typeof element === 'object' &&
        typeof element.toJSON !== 'function') {
      // remove circular-reference
      if (circularList.indexOf(element) >= 0) {
        return;
      }
      circularList.push(element);
      // if element is an array, then recurse with its elements
      if (Array.isArray(element)) {
        return '[' + element.map(function (element) {
          tmp = stringify(element);
          return typeof tmp === 'string'
            ? tmp
            : 'null';
        }).join(',') + ']';
      }
      return '{' + Object.keys(element)
        .sort()
        .map(function (key) {
          tmp = stringify(element[key]);
          return typeof tmp === 'string'
            ? JSON.stringify(key) + ':' + tmp
            : undefined;
        })
        .filter(function (element) {
          return typeof element === 'string';
        })
        .join(',') + '}';
    }
    // else JSON.stringify normally
    return JSON.stringify(element);
  };
  circularList = [];
  return JSON.stringify(element && typeof element === 'object'
    ? JSON.parse(stringify(element))
    : element, replacer, space);
};


// test circular reference
aa = { bb: 1}
// output: { bb: 1 }
aa.aa = aa
// output: { bb: 1, aa: [Circular] }
clone(aa)
// output: { bb: 1 }
/*
*/
```

full test case of my circular-json-stringify function available @ https://github.com/kaizhu256/node-utility2/blob/beta/test.js#L799
and
https://kaizhu256.github.io/node-utility2/build..beta..travis-ci.org/test-report.html

screen shot 2016-06-01 at 22 25 09


```
        local.testCase_jsonStringifyOrdered_default = function (options, onError) {
        /*
         * this function will test jsonStringifyOrdered's default handling-behavior
         */
            options = {};
            // test data-type handling-behavior
            [undefined, null, false, true, 0, 1, 1.5, 'a', {}, []].forEach(function (data) {
                options.aa = local.utility2.jsonStringifyOrdered(data);
                options.bb = JSON.stringify(data);
                local.utility2.assertJsonEqual(options.aa, options.bb);
            });
            // test data-ordering handling-behavior
            options = {
                // test nested dict handling-behavior
                ff: { hh: 2, gg: 1},
                // test nested array handling-behavior
                ee: [undefined],
                dd: local.utility2.nop,
                cc: undefined,
                bb: null,
                aa: 1
            };
            // test circular-reference handling-behavior
            options.zz = options;
            local.utility2.assertJsonEqual(
                options,
                { aa: 1, bb: null, ee: [ null ], ff: { gg: 1, hh: 2 } }
            );
            onError();
        };
```

**Comment by zkat** [comment]
Hey @kaizhu256! The team talked about this patch a bit, specially the idea of bringing lodash dependencies such as this one directly into the source, as well as the role this _particular_ function plays in the source, and things that have happened with it.

One thing to note here is that there's a good chance that, in the future, we will simply stop using this functionality because we'll stop just cloning `package.json` objects, and so this would no longer be necessary. Another is that it's easier to trust `lodash`'s implementation, and to leave the work to that library, than to maintain potentially tricky algorithms like these in our own sources.

Because of all that, we agreed to just close this PR, but I really appreciate the time you took to put both of these PRs together, and the intention of the patch. Thank you for submitting it <3

**Comment by kaizhu256** [comment]
ok

**Pull request closed without merging**
