### PR TITLE
Release: npm@6.1.0

### PR DESCRIPTION
**Pull request by zkat**
[Rendered CHANGELOG](https://github.com/npm/npm/blob/release-next/CHANGELOG.md)

### CODE REVIEW

**Review by iarna — APPROVED** [review]
🐑

**Comment by legodude17** [comment]
🎉

**Comment by iarna** [comment]
6.1.0-next.0 was released

**Comment by legodude17** [comment]
🎉🎉🎉🎉🎉🎉🎉

**Pull request closed without merging**
