### PR TITLE
band-aids issue 11119 when there is an empty skeleton of a module in …

### PR DESCRIPTION
**Pull request by cchamberlain**
This is the code I changed to get dedupe to pass -> https://github.com/npm/npm/issues/11119

Probably not the best solution but I am not aware of everything that's going on in this module.

### CODE REVIEW

**Comment by othiym23** [comment]
That looks good to me (although @iarna should double check, and that line probably needs a line comment explaining why that logic works the way it does, so the next person to read it doesn't have to share your confusion). Could you write a test based on the failure in #11119? Thanks for putting this together!

**Comment by cchamberlain** [comment]
@othiym23 - Yeah, I'd be happy to but working through some deploy issues at work so may be a day.

**Comment by iarna** [comment]
We're landing #10582 which touches this same code (and makes it easy to test this logic) so you may want to wait for that and then base your tests on what adds to `lib/test/tap/lifecycle.js`

**Comment by cchamberlain** [comment]
Sounds good, I will wait on that and circle back.

**Comment by iarna** [comment]
It's now merged and ready for you any time. =)

**Comment by cchamberlain** [comment]
With this corrupt structure:

image

Now prints this instead of the error that was occurring previously (I verified the Length error was still occurring with #10582):

image

Confirmed that removing the corrupt directory and rerunning dedupe works as expected.  I made an attempt at bypassing this directory as well as removing it but couldn't get those situations working right.  Seems like this isn't the location to do a rimraf in anyways, if there is a better area that I can intercept the package name and skip processing or purge, let me know.  I attempted skipping in filter-invalid-actions, but pkg name was not set and the hook did not work correctly

**Comment by cchamberlain** [comment]
Ugh.. looks like I squashed poorly.. I'll close this and reopen.

**Pull request closed without merging**
