### PR TITLE
deps: update node-gyp to 3.7.0

### PR DESCRIPTION
**Pull request by MylesBorins**
new version with many fixed bugs 🎉

### CODE REVIEW

**Comment by mistydemeo** [comment]
This includes the fix for Xcode 10, so it would be really great to see this make it into npm.

**Comment by MylesBorins** [comment]
I believe that npm 6.2.0 is floating this as a patch.

**Comment by MylesBorins** [comment]
Floating the fix to xcode that is

**Comment by zkat** [comment]
I did this by hand and managed to do some `request` juggling to eliminate the weird duplication.

**Pull request closed without merging**
