### PR TITLE
Added suppor for auth methods both root and scopes #16528 #16879

### PR DESCRIPTION
**Pull request by snirad**
added support for all auth methods for root and scopes
don't need to wait for changes in 
https://github.com/zkat/pacote/blob/latest/lib/fetchers/registry/fetch.js

### CODE REVIEW

**Comment by jozemlakar** [comment]
Added PR https://github.com/npm/npm/pull/16879 which also adds test for the cases. I whink that is a better PR to merge. But if not, at least use the tests from that PR.

**Comment by snirad** [comment]
@jozemlakar Agree that this need more testing, but I don't like the Idea of having 2 different request, one for global and one for scoped, I want both to have the same body. this simplify pacote, so it doesn't need to 'know' how to deal with each request, it also simplify testing & debugging. but this is just my opinion.

**Comment by jozemlakar** [comment]
@snirad agreed! You will notice that in https://github.com/npm/npm/pull/16879/commits/bfed855f4645671785cd3c433d01ed572ec5b9b4 i submitted yesterday there is only one implementation. I would rather not say mine is better than yours. As I said, use tests from my implementation and whatever of both implementations and get npm fixed!

**Comment by zkat** [comment]
This was superseded by #16879. Thanks for the contrib, though! 🎉

**Pull request closed without merging**
