### PR TITLE
docs: update troubleshooting links

### PR DESCRIPTION
**Pull request by watilde**
Following up for https://github.com/npm/npm/pull/15756. I updated the troubleshooting and the contribution guideline links in docs.

### CODE REVIEW

**Review by zkat — APPROVED** [review]
LGTM. I'll fix up the weird conflict on merge, since the actual patch is pretty small. :)

**Comment by zkat** [comment]
@watilde would you be so kind as to rebase this branch onto `release-next`?

**Comment by watilde** [comment]
@zkat Sure! I just did it :)

**Comment by zkat** [comment]
@watilde I moved this to next release! Thanks for the rebase <3

**Pull request merged**
