### PR TITLE
Put npm-debug.log file in the cache folder, not cwd

### PR DESCRIPTION
**Pull request by othiym23**
New version of #6181: This should prevent mishaps like #1548, while avoiding overly configurable options that make it hard to predict where the file will show up.

Fix #1584
Close #5252

### CODE REVIEW

**Comment by watilde** [comment]
I got it about what will happen for `npm-debug.log`. It's sensitive about disk size, so I think it's good if set a limit of a size saved log in npm.config. (also other properties too..?

Apart from that, maybe one change has needed at [here](https://github.com/npm/npm/blob/debug-log-in-cache/lib/utils/error-handler.js#L84):
```diff
-  else rm("npm-debug.log", reallyExit)
+  else rm(getLogFile(), reallyExit)
```

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now. Also, @isaacs apparently decided it needed to be closed out when he had a little boo boo with his git branches a few weeks ago, so we'd need to redo it anyway if we wanted to land it. Either way, this is a supportability feature that should be tackled as such.

**Comment by computersarecool** [comment]
So wait @othiym23 I am not sure what the outcome is here.

 The `npm-debug` file now gets put deep in this `../_logs` file correct? The location is not configurable - it has just been moved. Is this correct?

**Comment by kenany** [comment]
@computersarecool Right, the path is currently not configurable.

**Comment by blachawk** [comment]
Is this still the case?  any plans in setting up a custom path location for logs?  Sucks for me as this is buried in a hidden folder in windows called AppData.  Yeah I can get to it but I don't want to take a spaceship to the moon just get a better view of the sun either.

**Comment by danielo515** [comment]
So log output is not configurable ? What a shame.
This is incredibly inconvenient for CI environments, where several CI engines are able to report you error and success logs located on certain directories.

**Pull request closed without merging**
