### PR TITLE
add 'npm it' command

### PR DESCRIPTION
**Pull request by isaacs**
I keep wanting a command for `npm i && npm t` so I could do `npm it`.

Needs tests and docs, but leaving this here for my fellow CLI peops to weigh in on whether this is a good thing or an excessive thing.

### CODE REVIEW

**Comment by othiym23** [comment]
Aaglaglgalgaglaglahaghaga I want this ALL THE TIME. It might confuse some people's muscle memory, but YES THIS IS A GOOD IDEA:+1::japanese_goblin::ski::sunflower:

**Comment by othiym23** [comment]
Sounds good, we'll try to get this out next week if you want to put together some tests and docs!

**Comment by othiym23** [comment]
(and let's go ahead and do this against both 2 and 3)

**Comment by zkat** [comment]
Missing tests so I'm bumping until next week. Should be quick for me to write some basic ones for this.

**Comment by zkat** [comment]
Woe is me, if only SOMEONE would be willing to write tests + docs for this ;)

(I can take care of it, but it'll be a bit before I have time)

**Comment by iarna** [comment]
I'm removing the milestone from this because, at this moment, writing tests for this (which is what's needed to land it) is not scheduled for this week or next.

**Comment by mzgol** [comment]
Sometimes pruning is also needed, would it be worthwhile to have a shortcut for:
```
npm prune && npm install && npm test
```
?

**Comment by othiym23** [comment]
I don't think that's the dominant use case, @mzgol, and I'd like to keep this a simple, focused addition if we can.

**Comment by mzgol** [comment]
OK, fair enough.

**Comment by ashleygwilliams** [comment]
documentation added.

**Comment by iarna** [comment]
Tests look good: :sheep:

**Comment by othiym23** [comment]
Rebased against `release-3.4.0` and landed as 1ac3e088f495bdcba45949ede36e2ad5578f60aa, bcb04f67b3cd1cd454cbfa1f78bf80257fb1cde2, and b6c17ddc65ebcd68091c39fae1f04501cde792a6. This was a real team effort. Thanks, everybody!

**Pull request closed without merging**
