### PR TITLE
add support for nw.js

### PR DESCRIPTION
**Pull request by xueeinstein**
details please visit:
https://github.com/xueeinstein/nw-npm/blob/master/README.md

### CODE REVIEW

**Comment by KenanY** [comment]
Indentation seems off.

**Comment by othiym23** [comment]
What are you trying to do with this change? Why do these specific changes need to be made to npm itself, and within `nw-gyp`?

**Comment by xueeinstein** [comment]
This change is for nw.js to install node.js native modules. `nw-gyp` is forked and developed from `node-gyp`. It'll download our customized node.js header files for specified nw.js version, in this way the built binary file could be compatible with nw.js ABI. 

PS, this code snippet only execute when `nw_version` is set up in project `.npmrc`. __No other side effect if `nw_version` isn't set up__. (`nw.js` is renamed from `node-webkit`)

**Comment by xueeinstein** [comment]
@KenanY , sorry, my vim indentation setup doesn't follow npm coding principle. I have corrected it.

**Comment by othiym23** [comment]
I think this is too special-purpose to go directly into npm. I'd be amenable to extending the support we've added for [`--node-gyp`](https://github.com/npm/npm/commit/145af6587f45de135cc876be2027ed818ed4ca6a) to work with `nw-gyp` (if it's even necessary – that may work as a drop-in for the build scripts that `nw.js` projects use with a little futzing. But this isn't a general-purpose enough change to go into npm proper. Thanks for the time you spent putting it together and explaining your use case, though!

**Pull request closed without merging**
