### PR TITLE
test: add test for npm substack command

### PR DESCRIPTION
**Pull request by watilde**
Hi,

Many people often used this command, so I added a test for `npm substack` command. 
// jk, it's no problem to close this if any problems :+1:

Thanks.

### CODE REVIEW

**Comment by KenanY** [comment]
:+1: :laughing:

**Comment by faiq** [comment]
😂

**Comment by othiym23** [comment]
shhh you're not supposed to acknowledge that substack is there he's just sitting in the corner publishing modules all day and beeping

**Comment by watilde** [comment]
Oh I agreed with you. It was like a little bit spinal reflex, I'll be careful from now on! thanks.

**Pull request closed without merging**
