### PR TITLE
Bump marked-man version

### LINKED ISSUE #8984: man page renders post-grave content strangely
If this is just a bug in https://github.com/kapouer/marked-man, let me know and I'll re-file. I tried to figure out how NPM generates its manfiles, and I _think_ that's true, but I'm not sure!

I'm getting strangeness in my manfiles:

2015-07-17-191638_694x71_scrot
2015-07-17-191658_472x67_scrot

from these two examples, I would _guess the issue is having graves ( \` ) in a second-level heading ( `##` ) causes strangeness. These two examples both from the FAQ

### PR DESCRIPTION
**Pull request by steveklabnik**
This includes a bugfix, https://github.com/kapouer/marked-man/issues/4 ,
which

Fixes #8984

### CODE REVIEW

**Comment by othiym23** [comment]
Thanks for the detective work, Steve! We'll get this merged into next week's `npm@2.x` release, so the FAQ should start rendering for you correctly in 2 weeks.

**Comment by steveklabnik** [comment]
:confetti_ball: 

do i need to worry about the build failure here?

**Comment by othiym23** [comment]
> do i need to worry about the build failure here?

Not at all. I need to sit down and have a long heart-to-heart with Travis and npm's test suite, especially when Node 0.8 is involved. Thanks for asking, though.

**Comment by steveklabnik** [comment]
:+1:

**Comment by iarna** [comment]
This landed in `npm@2.13.3` and `npm@3.2.0`!

**Pull request closed without merging**
