### PR TITLE
fix: Intermittent EPERM issues when renaming Windows files during install

### LINKED ISSUE #12059: Intermittent EPERM issues when renaming Windows files during install
On npm@2.14.20:

```
2016-03-25T00:12:37.6515576Z npm ERR! Windows_NT 6.3.9600
2016-03-25T00:12:37.6515576Z npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2016-03-25T00:12:37.6515576Z npm ERR! node v4.4.0
2016-03-25T00:12:37.6515576Z npm ERR! npm  v2.14.20
2016-03-25T00:12:37.6515576Z npm ERR! path D:\npm-cache\mkdirp\0.5.1\package.tgz.1638249806
2016-03-25T00:12:37.6515576Z npm ERR! code EPERM
2016-03-25T00:12:37.6515576Z npm ERR! errno -4048
2016-03-25T00:12:37.6515576Z npm ERR! syscall rename
2016-03-25T00:12:37.6515576Z npm ERR! Error: EPERM: operation not permitted, rename 'D:\npm-cache\mkdirp\0.5.1\package.tgz.1638249806' -> 'D:\npm-cache\mkdirp\0.5.1\package.tgz'
2016-03-25T00:12:37.6515576Z npm ERR!     at Error (native)
2016-03-25T00:12:37.6515576Z npm ERR!  { [Error: EPERM: operation not permitted, rename 'D:\npm-cache\mkdirp\0.5.1\package.tgz.1638249806' -> 'D:\npm-cache\mkdirp\0.5.1\package.tgz']
2016-03-25T00:12:37.6515576Z npm ERR!   errno: -4048,
2016-03-25T00:12:37.6515576Z npm ERR!   code: 'EPERM',
2016-03-25T00:12:37.6515576Z npm ERR!   syscall: 'rename',
2016-03-25T00:12:37.6515576Z npm ERR!   path: 'D:\\npm-cache\\mkdirp\\0.5.1\\package.tgz.1638249806',
2016-03-25T00:12:37.6515576Z npm ERR!   dest: 'D:\\npm-cache\\mkdirp\\0.5.1\\package.tgz',
2016-03-25T00:12:37.6515576Z npm ERR!   parent: 'ssb2b' }
2016-03-25T00:12:37.6671853Z npm ERR! 
2016-03-25T00:12:37.6671853Z npm ERR! Please try running this command again as root/Administrator.
2016-03-25T00:12:37.6671853Z npm ERR! Please include the following file with any support request:
2016-03-25T00:12:37.6671853Z npm ERR!     D:\work\4\s\npm-debug.log
```

`npm-debug.log` is [here](https://gist.github.com/adriaanthomas/d22ccdcafab45739e337). This was an `npm install --force` with an empty cache directory (as the debug log shows), but clearly that did not help this time.

Clearing the cache sometimes helps, but just as often it will fail again on some package (not always the same one).

### PR DESCRIPTION
**Pull request by adriaanthomas**
Copying behaviour of fix for #9696. Fixes #12059.

### CODE REVIEW

**Comment by iarna** [comment]
Seeing as the rename happens in `write-stream-atomic` I'd really much prefer a fix go in there, so we can take advantage of it everywhere. I still find just ignoring these errors troubling as I feel like it means the cache is in an undefined state– we _think_ we downloaded a new tarball, but the tarball we downloaded isn't there and… I don't know what is? Something I didn't want?

**Comment by jeerbl** [comment]
Is this still being reviewed? Or is it still being developed?

**Comment by adriaanthomas** [comment]
Sorry, I have not had time to dig in to this further. We're currently running with this (manually applied, because of #12274) on our build servers and several laptops, and have not had any issues since, whereas before, many npm installs were failing.

This approach (i.e. ignoring certain errors) I took from #10940, as this seems a very similar situation (just not for `package.json` but for for the tgz of the actual package).

If we want to fix the underlying issue, instead of working around it, I think that would require quite some work. Clearly `graceful-fs` [attempts to do the same thing](https://github.com/isaacs/node-graceful-fs/blob/master/polyfills.js#L76) but for us at least, in many situations this is not enough. I tried increasing the timeout there, while that sometimes made things better, errors still occurred.

Fixing (or working around) this in `write-stream-atomic` scares me a bit, because here at least we have a fairly good idea of what is going on, whereas in a generic library the actual situation is much harder to predict.

When I find some time I'll look into this further. Of course I'd be very interested if someone can think of a different solution.

**Comment by tjwebb** [comment]
+1. This issue is rendering AppVeyor CI useless

**Comment by jonathandelgado** [comment]
+1 - Even if this is a temporary fix, it is extremely needed for windows. Having to rerun every other npm command is tedious.

@iarna thoughts?

**Comment by codeimpossible** [comment]
FYI I submitted [a PR to patch fs-write-stream-atomic](https://github.com/npm/fs-write-stream-atomic/issues/13), we've been running it in our CI builds for the past two weeks with no issues - and no more `EPERM` failures. Any feedback would be awesome!

**Pull request closed without merging**
