### PR TITLE
test: `clone()` with circular dependencies. Fix #11370

### LINKED ISSUE #11370: Add failing test for JSON clone
My commit 1d1ea7eeb958034878eb6573149aeecc686888d3 broke some packages under 3.7.0 that had circular references by the time they reached this clone. Currently no tests cover this issue. We need to add one to ensure it can't happen again.

### PR DESCRIPTION
**Pull request by dirceu**
Add regression test so issues like #11349 won't happen again.

Fixes: #11370

### CODE REVIEW

**Comment by iarna** [comment]
I tried this with 25f297a and it doesn't fail, so it seems this test doesn't reproduce the problem we encountered. It's not circular dependencies that cause issues, we have those all the time, it's package metadata that ends up with cycles in it. (It's not even clear to me _how_ this happens, tracking that down too would probably be useful.)

**Comment by dirceu** [comment]
Thanks for the feedback! This test fails for me against the version of `clone` from https://github.com/npm/npm/commit/1d1ea7eeb958034878eb6573149aeecc686888d3; for instance, it fails if I edit `lib/fetch-package-metadata.js` like this:

```diff
- var clone = require('lodash.clonedeep')
+ var clone = function (obj) { return JSON.parse(JSON.stringify(obj)) }
```

... and passes with the current version of clone (from `lodash.clonedeep`).

**Comment by iarna** [comment]
Ah yeah, I apparently pasted the wrong hash in 🙃

**Comment by iarna** [comment]
Ideally I'd like to see a version of this that doesn't use the network (that uses `npm-registry-mock` as a fake registry).

**Pull request closed without merging**
