### PR TITLE
added example for homepage

### PR DESCRIPTION
**Pull request by cg-cnu**
Added example for homepage usage in package.json in the documentation.

### CODE REVIEW

**Comment by cg-cnu** [comment]
Hi, Not exactly sure why the build is failing. Let me know if I need to raise the pr to a different branch. Thanks!

**Comment by nwoltman** [comment]
Don't worry @cg-cnu, the tests are just broken right now so everyone's builds are failing.

**Review by zkat — APPROVED** [review]
LGTM! Thanks for the patch :)

**Comment by cg-cnu** [comment]
Thanks @zkat 😄

**Pull request merged**
