### PR TITLE
lifecycle: propagate SIGTERM to child

### PR DESCRIPTION
**Pull request by daniel-pedersen**
When one runs for example `npm run-script`, any SIGTERM to npm will orphanize the child process. This is a simple fix for this (potential) issue. Now whenever npm launches a child through lifecycle, any SIGTERM signal is simply propagated to the child for the duration of the process.

This behavior of npm when getting a SIGTERM seems to be what makes sense to most people (see the discussion in #4603), and makes `npm run-script` more friendly in various development scenarios.

### CODE REVIEW

**Comment by iarna** [comment]
This looks pretty reasonable to me. It does still need a test.

**Comment by daniel-pedersen** [comment]
Hmm. Something weird is going on. Testing with my linked npm in the shell, the child process is orphanized. For example, using `npm start` with the following `package.json`,
`{ "scripts": { "start": "node -e 'process.stdin.resume()'" } } `
and then doing
`$ kill <npm_pid>`
in another tab results in a orphanized node process without my first commit, with my commit the child is also terminated.

But I've now been trying to reproduce this in the commited unit-test, so that the test fails without my first commit and passes with it, but to no avail.

**Comment by daniel-pedersen** [comment]
Done! The new test fails and hangs without my previous commit, which passes it.

**Comment by iarna** [comment]
Awesome, thank you!

**Comment by zkat** [comment]
I was considering whether to pull this into the 2.x LTS, and came to the conclusion that while folks may really not want to have orphaned zombies just from a `^C`, there is, in fact, a chance that someone out there is already relying on this behavior.

Because of that, and because LTS is supposed to be more careful about stuff like this, I'm not gonna merge this into LTS. If anyone has other thoughts or objections, please feel free to chime in, since it's not set in stone. :)

**Comment by iarna** [comment]
This landed in 3.8.1!

**Comment by gaastonsr** [comment]
Freaking awesome @daniel-pedersen

**Comment by dchambers** [comment]
Hey guys, is this known/expected to work on Linux? I can see that it works on MacOS, but it doesn't seem to be working on our UAT box which is running Ubuntu Server?

**Comment by kucharskimaciej** [comment]
Seconding @dchambers on this. Make for quite annoying experience when automating tasks with npm.

**Comment by twang2218** [comment]
I'm using docker with `npm start`, and the npm doesn't forward the signal to child-processes, which caused graceful shutdown failed, and the app process be SIGKILLed instead, without a chance to release the resources.

Are you sure this PR is working on Linux? My NPM version is `3.10.10`

```bash
$ npm -v
3.10.10
$ node -v
v7.2.1
```

**Comment by dchambers** [comment]
Hey @twang2218, it may be worth creating a new issue specifically for Linux support as this has been closed quite some time now.

**Comment by addaleax** [comment]
Yes, this isn’t working, at least with bash; npm runs its lifecycle processes in a shell, and bash doesn’t forward SIGTERM to its children.

**Pull request closed without merging**
