### PR TITLE
translation typo

### PR DESCRIPTION
**Pull request by devmount**

### CODE REVIEW

**Comment by kenany** [comment]
Why does _verboten_ not work here?

**Comment by devmount** [comment]
Is *verboten* an actual English word? Didn't know that... It is the German word for *prohibited* or *forbidden*... I thought that was meant here.

**Comment by kenany** [comment]
Seems like it is: [this page](http://www.wordnik.com/words/verboten) says it's in _The American Heritage® Dictionary of the English Language, 4th Edition_, and [this page](http://www.thefreedictionary.com/verboten) lists a couple more (admittedly unknown to me) sources.

**Comment by devmount** [comment]
I see. In that case, just delete my PR. I thought it was a mistake and was confused to read a German word here.

**Comment by kenany** [comment]
I wouldn't say that this need to be deleted so quickly. One could argue that "forbidden" is a more familiar word to English speakers, so perhaps this could be accepted as an improvement to the docs. I'll leave it to the rest of the team to decide.

**Comment by zkat** [comment]
_verboten_ is indeed an English word, but I also like _forbidden_ much more!

**Review by zkat — APPROVED** [review]
LGTM! Forbidden is probably easier to understand anyway :)

**Pull request merged**
