### PR TITLE
The repo, as its checked in, has `npm ls` errors:

### PR DESCRIPTION
**Pull request by iarna**
```
npm ERR! missing: glob@^5.0.3, required by init-package-json@1.9.1
npm ERR! missing: has-unicode@^1.0.0, required by gauge@1.2.2
npm ERR! missing: has-unicode@^1.0.0, required by gauge@1.2.2
npm ERR! missing: has-unicode@^1.0.0, required by gauge@1.2.2
npm ERR! missing: glob@^5.0.3, required by read-package-json@2.0.2
```

This happened because of the `glob` and `has-unicode` major release updates, and went undetected because the actions necessary to run the tests (which check for this sort of thing) resolved the missing modules.

The version published to the registry is also missing these things, however if you're updating from a previous 3.x release, it will fix up the install when you do the update, installing the versions listed above in addition to the bundled deps. If you're upgrading from a 2.x release, it won't, but this won't break anything because the breaking changes in `glob` & `has-unicode` don't have negative effects for us, and node doesn't care about version numbers when loading modules.

This PR fixes this problem by updating `init-package-json` and `read-package-json` to use the new glob, and updating `gauge` to use the new `has-unicode`, and then, since `gauge` isn't a direct dependency of npm, reinstalling the existing versions of `npmlog` & `node-gyp` which were the two top level dependents that used `gauge`.

### CODE REVIEW

**Comment by othiym23** [comment]
Rubberstamp :sheep: because the logic sounds good and the diff is too large for anything other than a double-check of `package.json`.

**Comment by iarna** [comment]
Yeah, the diff is 90% removing duplicate copies of readable stream by weight.

**Comment by iarna** [comment]
It looks like this breaks installs from 3.3.12 (https://github.com/npm/npm/issues/11088#issuecomment-172931543)

**Comment by iarna** [comment]
This was merged to 3.5.5! =)

**Pull request closed without merging**
