### PR TITLE
upgrade to node-gyp@1.0.3 fixes customFds warning

### PR DESCRIPTION
**Pull request by jeffbski**
Upgrade bundled node-gyp from v1.0.2 to v1.0.3 which fixes the warning

```
customFds option is deprecated, use stdio instead.
```

Projects which use npm to run node-gyp continue to get this error until this version is published with latest npm.

### CODE REVIEW

**Comment by jeffbski** [comment]
Details of the customFds fix is here:https://github.com/TooTallNate/node-gyp/pull/533

**Comment by othiym23** [comment]
Excellent! This will make @trevnorris happy, or at least less annoyed. I'm away from my computer right now, so I'll merge this tonight. Thanks, Jeff!

**Comment by jeffbski** [comment]
My pleasure. :-)

**Comment by trevnorris** [comment]
whoot!

**Comment by othiym23** [comment]
Landed as a91f2c7c9a5183d9cde7aae040ebd9ccdf104be7. Thanks, Jeff!

**Comment by jeffbski** [comment]
Awesome!

**Pull request closed without merging**
