### PR TITLE
config: Set process.env.no_proxy in adaptConfig

### PR DESCRIPTION
**Pull request by legodude17**
Solution for #7168.

### CODE REVIEW

**Comment by othiym23** [comment]
Here's what needs to be added before this will be ready to merge:

- [ ] The configuration variable name should follow the convention of the CLI's other configuration, and use a hyphen instead of an underscore (`no-proxy`).
- [ ] It also will need to be added to `lib/config/defaults.js` (the tests won't pass otherwise – this is part of how the project ensures that all of the CLI's configuration is documented), and have a sensible type and default set. See the rest of that file to get the gist of how that works. It's a little tricky, because `nopt` will typically try to convert a `no-<name>` config setting into a boolean set to a falsy value, so this also probably needs 
    - [ ] a few additional test cases in the current config tests to ensure that nothing untoward happens as a result of this change.
- [ ] A few general tests that the behavior makes it to the child environment of run-scripts as `no_proxy` is probably a good enough test, because the CLI doesn't really have control over `request`.
- [ ] Also, `doc/misc/npm-config.md` will need an update to include information about the new configuration, and the existing documentation doesn't mention `no_proxy` / `NO_PROXY`'s functionality, even as it currently stands, so that could probably use some cleanup overall, and cross referencing between the sections for `proxy`, `https-proxy`, and `no-proxy`.

Let us know if you have any questions about any of the above, and thanks for the contribution!

**Comment by legodude17** [comment]
Thanks for the quick feedback. I was wondering what the default should be in `lib/config/defaults.js`. I think it should be `null`, but I was wondering what you thought.

**Comment by legodude17** [comment]
Where should the tests go in the folder structure? I am still a little unclear about where the tests go and what organization system they have.

**Comment by legodude17** [comment]
Any updates? I just need to find a bit of time to write some tests. The docs are done, can I get feedback on them?

**Comment by iarna** [comment]
All tests go in `test/tap/`

**Comment by legodude17** [comment]
Should I make some new files or piggyback on some existing ones?

**Comment by jd-carroll** [comment]
What's the status of getting this merged?  Just setup an internal registry and this is suddenly going to become a problem for 200+ developers internally.

**Comment by legodude17** [comment]
@jd-carroll I need to find some time to write tests, and then someone from `npm` needs to resolve all of the merge errors.

**Comment by jd-carroll** [comment]
Would it make sense to close this PR and open a new one just to avoid all of the merges?

**Comment by legodude17** [comment]
That was an idea I had. Is there anyone who wants to continue this?

**Comment by iarna** [comment]
As suggested I'm going to close this but if it's something you're still interested please feel free to open a new PR based on `latest`.

**Pull request closed without merging**
