### PR TITLE
Add my changelog generator tool

### PR DESCRIPTION
**Pull request by iarna**
Freshly ported to JS =p

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
👀 i'd love to hear more about this tool

**Comment by othiym23** [comment]
@iarna Is there any particular kind of review you'd like there to be of this? It might be nice to prepend a comment to the script describing how you personally use it, and having a `Makefile` task for it might be helpful, but since this is a tool for our own internal use, I'm inclined to just land it to master and iterate as we find new ways to improve it.

**Comment by iarna** [comment]
I wasn't looking for anything in particular. Mostly I just wanted to get it off my hard drive.

**Comment by iarna** [comment]
@ashleygwilliams This is gonna land without more discussion here, but I'd love to talk with you about it!

**Comment by iarna** [comment]
This was merged to 3.6.0! =)

**Pull request closed without merging**
