### PR TITLE
Update build status branch in README

### PR DESCRIPTION
**Pull request by zkat**

### CODE REVIEW

**Comment by legodude17** [comment]
`Build: Failing`? 😆

**Comment by KenanY** [comment]
This is already covered by https://github.com/npm/npm/pull/14430, no?

**Comment by othiym23** [comment]
@KenanY We're probably not going to land #14430, for reasons that I'll enumerate over there in a bit.

**Review by iarna — APPROVED** [review]

**Comment by iarna** [comment]
Merged into `release-next`!

**Pull request closed without merging**
