### PR TITLE
doc: Convert typewriter apostrophes to typographic apostrophes

### PR DESCRIPTION
**Pull request by svenheden**
- Convert typewriter apostrophes to typographic apostrophes where appropriate
  - Info on this: http://www.brunobernard.com/en/more-elegant-texts-with-typographic-apostrophe/
- Add backticks where appropriate
- Title case "Node" as this is a proper noun :)
  - https://github.com/nodejs/node/pull/3998

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
zomg! this is great. thank you @jonathanp! doc changes in this repo take a second to land because of npm's release cycle, but we'll def get this merged and shipped. :sparkling_heart: :dolphin:

**Comment by ashleygwilliams** [comment]
if you are interested... the https://github.com/npm/docs/tree/master/content repo could probably also use these changes! (if you make a PR there i could merge and publish that today :wink:)

**Comment by othiym23** [comment]
This may take a little while to merge, because I need to make sure this doesn't break rendering of the help on the command line in both regular terminals and on Windows. If that checks out, and you're interested in seeing these changes land in `npm@2` LTS, it probably makes sense to float this as a separate patch for `npm@2`, because the docs have diverged enough that I don't think it would be a clean apply.

Orrrrr... this could be added as a transform applied during the docs build step. I don't know if you're interested in that, @jonathanp, but it would have the significant benefit of making sure that all the docs going forward also use typographic quotes and apostrophes consistently. Let me know if that's something you'd be interested in playing around with and I can give you more detail on how the CLI docs get built.

**Comment by jonathanp** [comment]
Thanks for the offer @othiym23! I think the transform is a good idea but I'm afraid I don't have time for developing that. If you do I understand if you go with that solution and don't merge this PR :)

**Comment by iarna** [comment]
We're closing this pull request as it has gone sixty days without activity.  In our experience pull requests that go this long are unlikely to land.  If you have updates to it, please feel free to open a new pull request.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).

**Pull request closed without merging**
