### PR TITLE
Fix: show settings from per-project .npmrc file in "npm config list"

### LINKED ISSUE #11472: "npm config list" ignores per-project .npmrc
I created an empty directory and executed this:

```
> echo foo=1234 > .npmrc
> npm -v
3.7.1
> npm config get foo
1234
```

which looks ok. But if I execute `npm config list` in the same directory, the `foo` setting does not show up. Same on Windows and Linux.

Is this expected behavior or a bug?

### PR DESCRIPTION
**Pull request by mjomble**
Fixes #11472

### CODE REVIEW

**Comment by iarna** [comment]
I'd like to see a test for this.

**Comment by mjomble** [comment]
Ok, I can look into adding some

**Comment by mjomble** [comment]
I've added a test now.

I noticed there were no tests at all for `npm config list` and although it would be nice to also have tests for other config types (cli, env, user, global), I felt they were outside the scope of this PR. So I only implemented a test for per-project conf for now and added a TODO comment for implementing the others.

The Travis build failed in 0.8, but it seems like a generic configuration issue that is not related to this PR. I noticed a similar failure in a different PR as well. For >= 0.10, all builds are passing.

**Comment by iarna** [comment]
The 0.8 failure is, as you assume, not related to your PR. (Ordinarily 0.8 does pass– I've flagged it for a rebuild. It's an issue we've visited earlier, and is related to a bug in 0.8's `http` module that we've papered over as best as we were able, unfortunately it still seems to show up, albeit much less often.)

**Comment by iarna** [comment]
(I also agree that other tests are out of scope here. They'd be fantastic, but are hardly required for this PR.)

**Comment by mjomble** [comment]
Maybe I'll look into the other tests once this PR gets merged :)

**Comment by iarna** [comment]
Thank you for putting this all together, LGTM

**Comment by iarna** [comment]
This landed in 3.8.2!

**Pull request closed without merging**
