### PR TITLE
dezalgo childDependencySpecifier cb to prevent recursive process.nextTick

### LINKED ISSUE #12754: Sporadic "warning: Recursive process.nextTick detected." followed by "RangeError: Maximum call stack size exceeded" on node 0.10.42 when running "npm install" on an existing node_modules tree.
broken npm versions: **3.9.2** (at least **3.9.0** and above seem to be affected) 
working npm version: **3.6.0** does not have this issue. I haven't bisected any further as it's hard to reproduce

node: **0.10.42**
OS: **OS X El Capitan (10.11.4) / Darwin 15.4.0 Darwin Kernel Version 15.4.0**

**UPDATE**:

Looks like it's something about childDependencySpecifier that was introduced in e928a30 that causes an infinite recursion of some kind.

Reproduction is tricky, but when `install`ing on an existing tree with some unknown condition, we get this:

```
$ npm install
npm http request GET https://unpm.uberinternal.com/raven-js
npm http 200 https://unpm.uberinternal.com/raven-js
fetchMetadata → 200       ▄ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
...
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

console.js:62
  this._stderr.write(util.format.apply(this, arguments) + '\n');
                                 ^
RangeError: Maximum call stack size exceeded
```

I've seen this happen a few times with very specific module trees... I'm working on a generic reproduction steps.

**UPDATE**:

I was able to retrieve the stack via overriding process.nextTick method with a thing that logs the stack once in a while:

```
...
    at Console.warn (console.js:62:16)
    at maxTickWarn (node.js:412:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at process.<anonymous> (/usr/local/lib/node_modules/stackup/node_modules/async-listener/index.js:18:15)
    at process._nextTick [as nextTick] (/usr/local/lib/node_modules/npm/bin/npm-cli.js:14:12)
    at requestFlush (/usr/local/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap/raw.js:95:17)
    at rawAsap (/usr/local/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap/raw.js:18:9)
    at asap (/usr/local/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap/asap.js:26:5)
    at dezalgo (/usr/local/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:8:3)
    at wrapper (/usr/local/lib/node_modules/npm/node_modules/wrappy/wrappy.js:24:18)
    at andForEachChild (/usr/local/lib/node_modules/npm/lib/install/deps.js:283:10)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:382:6)
    at Array.0 (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:298:5
    at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:354:21
    at /usr/local/lib/node_modules/npm/lib/install/and-add-parent-to-errors.js:7:24
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:429:11
    at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:442:5
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:165:5
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:43:25
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:90:7
    at /usr/local/lib/node_modules/stackup/node_modules/async-listener/glue.js:188:31
    at process._tickCallback (node.js:448:13)
```

### PR DESCRIPTION
**Pull request by lxe**
Fixes #12754

### CODE REVIEW

**Comment by lxe** [comment]
Similar PR: #12731 by @JensEggers. I used `dezalgo` in the spirit of consistency, but it does the same-ish thing: https://github.com/kriskowal/asap/blob/master/raw.js#L92

**Comment by zkat** [comment]
I was about to point out that #12731 seemed like a duplicate -- I'd still like to get some tests around this before merging, but either patch might work?

**Comment by lxe** [comment]
@zkat either one works. This one is a bit more consistent with the rest of npm code, using dezalgo to defer the callback. I also  added a unit test.

**Comment by lxe** [comment]
Looks like tests are failing for separate reason. Both the windows and the linux test logs show that the childDependencySpecifier unit test succeeded as expected:

**Comment by lxe** [comment]
A gentle bump. Looks like the problem still persists in @latest.

**Comment by zkat** [comment]
This LGTM. :) I asked @iarna to take one more look at it before I include it, but it should be fine, I think,

**Comment by iarna** [comment]
Thank you for putting this together! What would you say to using `asap` here, instead of `dezalgo`? The thing is, this is already zalgo-free, that's not actually the problem, the problem is `process.nextTick` yelling at us. ;) `asap` is what `dezalgo` uses under the hood, so while it's not currently a direct dependency of npm's, we're already including it in our dependency tree.

**Comment by lxe** [comment]
@iarna I wanted to `asap`, but since it's not a direct dependency, I used dezalgo isntead, which uses it. I can add asap as a dep. 

Also there technically is a theoretic case in here where dezalgo is better:

```
childDependencySpecifier:
  if (tree.resolved[name][spec]){ return cb(); }
  realizePackageSpecifier(... function () { cb() })
```

We might have a stack in the same tick like this:

```
childDependencySpecifier
realizePackageSpecifier
cb
childDependencySpecifier
cb
```
unless we are sure that `realizePackageSpecifier` de-zalgos it's own callback...

**Comment by lxe** [comment]
A gentle bump. This still happens preventing me from upgrading.

**Comment by iarna** [comment]
(Yes, realizePackageSpecifier dezalgos its callbacks already.)

Closing in favor of #13021

**Pull request closed without merging**
