### PR TITLE
shrinkwrap: do not fail on optional dependencies

### PR DESCRIPTION
**Pull request by mantoni**
If an optional dependency was not installed, shrinkwrap fails with a message saying that a required dependency is missing. This patch checks whether a missing dependency was listed in the optionalDependencies.

I was seeing this with `fsevents` not being installed as a dependency of `chokidar`. I made sure the test case produces the exact same error and that the patch fixes it.

### CODE REVIEW

**Comment by mantoni** [comment]
Fixed the stylistic issues which the build complained about. It's all shiny green now, except for the Node 0.8 build which has some issues with the install process. I can't do anything about this one, I guess.

@iarna @zkat Is this an acceptable solution? Is there anything else that should be improved?

**Comment by iarna** [comment]
Yeah, this seems like the right thing to do. I'm adding this to tomorrow's release.

**Comment by iarna** [comment]
Hi, thank you for this! It shipped with 3.3.7 just yesterday. =)

**Comment by mantoni** [comment]
Oh cool, that went into a release really quickly! Thanks.

**Pull request closed without merging**
