### PR TITLE
Tests that use the network...

### PR DESCRIPTION
**Pull request by iarna**
This PR has two things:
1. Patches for four tests to make them no longer use the network
2. Move the remaining 10 tests that require the network into `test/network`

`npm run test` will still run the network tests but this makes it easy to skip them if we have need to with `npm run tap test/tap/*.js`. It also acts as documentation of which tests remain to be converted.

### CODE REVIEW

**Comment by othiym23** [comment]
Good idea, and good work! If the tests are green on Travis, LGTM! :sheep::rocket::fire:

**Comment by iarna** [comment]
Will merge when green

**Comment by iarna** [comment]
(I canceled the push CI build since it's identical to the PR build)

**Comment by iarna** [comment]
Merged into `release-next`.

**Pull request closed without merging**
