### PR TITLE
configuration setting to never delete symlinks

### PR DESCRIPTION
**Pull request by ghost**
This patch turns off pruning for symlinks and packages inside of symlinked directories.

This patch would mitigate the effects of https://github.com/npm/npm/issues/17257
and may still be wanted behavior once that bug is fixed.

Related no-auto-prune feature: https://github.com/npm/npm/pull/18921

### CODE REVIEW

**Comment by fstoerkle** [comment]
@substack looking at the Travis CI build, I guess you need to add a default for this new option in https://github.com/npm/npm/blob/latest/lib/config/defaults.js

**Comment by zkat** [comment]
Gonna hold off on this PR until @iarna is back from conference stuff so we can actually talk about it.

**Comment by jimsugg** [comment]
See also #17287. Please expedite this if possible.

**Comment by billiegoose** [comment]
OH MY GOD - this is why I got so frustrated and blew away all of my repos and reinstalled them all from scratch on Friday... I was going crazy. Here is what was going on:
1. git clone foo; cd foo
2. npm i
3. npm link foo-common # our development copy of foo-common is developed in tandem with foo
4. npm i --save new-dependency

and now the "npm link" to foo-common is messed up.

I'm not 100% sure this is the exact steps and the cause of the problem... but I will test on Monday when I get into work.

**Comment by jbcpollak** [comment]
Steps 2, 3, 4 are repeatable and consistent no matter what you do prior to
them. In fact step 4 could just be `npm i` - any `npm install` after
linking will blow away your locally linked repos.

>

**Comment by AndreiShostik** [comment]
@zkat, @iarna was back from a conference?
guys, please, review.
it turned into a very annoying thing to come up with workarounds to return back symlinks

**Comment by zkat** [comment]
@substack the latest release added a mode where autoprune only happens if you're running with package locks/shrinkwrap enabled. I believe this solves your specific use-case without adding this flag.

We're going to have a better workflow around links in general when `npm@6` comes out, and overhauling link is literally the reason for that breaking change.

Are you ok enough with having this closed for now?

**Comment by ljharb** [comment]
@zkat even with a lockfile i don’t want the pruning behavior; it breaks anything i set up in a postinstall script, links or not. It’d be really great to get this merged.

**Comment by bluelovers** [comment]
need this lol

**Comment by zkat** [comment]
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

**Pull request closed without merging**
