### PR TITLE
node-gyp: upgrade to v3.3.0

### PR DESCRIPTION
**Pull request by rvagg**
Notable changes:
- Support for building on AIX
- Upgrade to gyp b3cef02
- Add --cafile command line option
- Allow for npmlog@2.x
- Download headers tarball for ~0.12.10 || ~0.10.42
- Introduce NODEJS_ORG_MIRROR and IOJS_ORG_MIRROR

Suspecting that I may not have this quite right since there's a lot of stuff going on in node_modules/node-gyp/node_modules. npmlog has gone cause it can now use the top-level version but there's other stuff going on that may not be as helpful. Let me know if something's awry that I can fix or if you'd rather just do this yourself.

My primary interest is in the headers tarball change, the MIRROR env vars change is helpful too on a path to removing the `NVM_*` variants. Once this goes in we should be able to ship this with a new 0.10 and 0.12 I think. 0.10 is waiting for that 1->2 upgrade.

### CODE REVIEW

**Comment by zkat** [comment]
yay! Thanks -- this is the bit I needed for #11528 to be done. I'll take a look in the morning and get everything settled. Here's hoping this makes CI happy :)

**Comment by othiym23** [comment]
Thanks, @rvagg! We'll try to get this into this week's releases of `npm@master` and `npm@lts`.

**Comment by zkat** [comment]
Hey, @rvagg -- I did this as part of #11528 (which existed prior) and credited you in the commit. I'm gonna close this one in favor of that one. Thanks a bunch for getting this release out the door! :)

**Comment by rvagg** [comment]
rad, credit was unnecessary but thanks anyway

@zkat would you mind putting a PR to v0.12-staging and v0.10-staging on your TODO to get the latest npm@2 on those branches? I'm assuming here that it's going to be messy enough to not be able to reuse the latest commits that did it for v4.x-staging.

**Pull request closed without merging**
