### PR TITLE
feat: allow custom shell for run-script

### PR DESCRIPTION
**Pull request by mmkal**
Addresses https://github.com/npm/npm/issues/6543

Maybe I'm under-thinking the problem, but this seems to work for me. I can set
`command-shell = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`
or
`command-shell = C:\Windows\System32\bash.exe`
in my `.npmrc` and it just works.

~I'm guessing tests would go in https://github.com/npm/npm/blob/latest/test/tap/run-script.js, but I'd be interested to hear thoughts on the approach before I go that far.~

### CODE REVIEW

**Comment by mmkal** [comment]
@othiym23 @isaacs @majgis any thoughts on this?

**Comment by misha-kaletsky-zocdoc** [comment]
@zkat ?

**Comment by mmkal** [comment]
@zkat ?

**Comment by mmkal** [comment]
I'm going to keep trying to bump this, as it would greatly improve development experience on Windows... @KenanY @zkat @watson @iarna

**Comment by kenany** [comment]
I'll defer to the other members to review this.

**Review by zkat — CHANGES_REQUESTED** [review]
Okay! We got to discussing this, and we decided to take this PR, pending one change:

Could you change this to `script-shell`? It's a bit of a bikeshed, but we decided this is a more fitting name in general.

Once that change happens, and the test suite passes, we'll merge this in! 🎉  Thanks a bunch for the PR!

**Review by zkat — APPROVED** [review]

**Comment by zkat** [comment]
Cool beans 🐻

**Comment by mmkal** [comment]
@zkat thanks!

**Comment by danielbayley** [comment]
@zkat Could we be able to set the shell somewhere in `package.json`, rather than necessarily having to have an `.npmrc` file to utilise this feature?

Maybe something like:
~~~ json
"config": {
  "script_shell": "/bin/zsh"
}
~~~
or even
~~~ json
"scripts": {
  "shell": "/bin/zsh"
}
~~~

**Comment by mmkal** [comment]
@danielbayley that should already work on npm 5.1.0+ if you use 
```
  "config": {
    "script-shell": "/bin/zsh"
  }
```

ie use a hyphen rather than an underscore.

See https://docs.npmjs.com/misc/config - that's a valid way to set config values.

**Comment by iarna** [comment]
@mmkal 

The `config` section of `package.json` is used as a way of passing values to run scripts, but it's not used by npm itself to load configuration. Sorry, those docs could be clearer.

`publish-config` _is_ but only during publication.

The usual approach would be to have this as a project-local `.npmrc`, which is already supported. Just drop one in next to your `package.json`. Be aware that setting this to something truely exotic (like `tcsh`) may break some dependencies as this setting is per-project, not per-module. That is, we don't read `.npmrc` files from modules when we install them.

**Comment by mmkal** [comment]
Ah, sorry, didn't realise. In that case I agree with @danielbayley !

**Comment by danielbayley** [comment]
Also, I tried to utilise this with `npm config set script-shell node_modules/.bin/shx`

But for some reason it doesn't work… I'm not sure if the problem is with npm or [shx], so I posted on both and linked…

~~~ ini
# .npmrc
script-shell = node_modules/.bin/shx
~~~
~~~ js
// package.json
"scripts": {
  "test": "echo something" // fails! :/
}
~~~
~~~ sh
> npm test
Error: Missing ShellJS command name

npm ERR! Test failed.  See above for more details.
~~~

[shx]: https://github.com/shelljs/shx/issues/117

**Comment by mmkal** [comment]
I suspect that is because shx is not a real shell, just a wrapper for a small number of commands. So invoking it like `shx -c "echo something"` (which is effectively what npm does) won't work. It'd probably be easier to fix in shx than npm - they'd just need to support the -c flag. But there'd still be a lot of missing shell features. Maybe a better solution would be another npm module that ships a small node executable script acting as a shell wrapper. The wrapper could use powershell on windows and bash on *nix.

**Comment by danielbayley** [comment]
@mmkal Thanks for the tip-off. I fixed it in https://github.com/shelljs/shx/pull/118.

@iarna Thanks for the clarification. I have it working with `.npmrc`, but for many projects that otherwise don’t need that file, the ability to set the shell somewhere in `package.json` would definitely be preferable.

**Pull request merged**
