### PR TITLE
Add test to document issue in current version of npm-packlist

### PR DESCRIPTION
**Pull request by jameshulse**
Fixed by pull request on `npm-packlist`: https://github.com/npm/npm-packlist/pull/5
Fixes issue on npm: https://github.com/npm/npm/issues/17560

### CODE REVIEW

**Review by zkat — APPROVED** [review]
Awesome! Thanks for this test! Files-and-ignores stuff has always been such a persnickety thing. It's nice to have more detail in this test file in particular 👍

**Comment by jameshulse** [comment]
Happy to help!

I am wondering where this PR sits on the validity for free socks scale though 🙄

**Comment by zkat** [comment]
@jameshulse free socks are a `documentation` thing 🙈

**Comment by jameshulse** [comment]
oh no 🙉 on my way to the documentation repo then...

**Comment by zkat** [comment]
I want to take more time merging the PRs to `npm-packlist`, because that tends to be a pretty high-risk merge and I wanna make sure to review it more thoroughly, so I'm gonna push merging this one out a bit.

**Comment by zkat** [comment]
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

**Pull request closed without merging**
