### PR TITLE
extract: support corguments

### PR DESCRIPTION
**Pull request by iarna**
This replaces the package manifest in the ideal tree with one read off disk and merged with what we got from the registry

### CODE REVIEW

**Review by zkat — CHANGES_REQUESTED** [review]
The changes basically match the stuff I've been testing with, so LGTM on that front. This should really get some tests, though.

**Comment by iarna** [comment]
hmm, I guess a test where we inject a corgument and assert that we got the package.json version in the installed package…

**Comment by zkat** [comment]
@iarna https://github.com/zkat/pacote/blob/latest/test/util/mock-tarball.js would this help

**Comment by iarna** [comment]
I usually just make a teeny-tiny minimal tarball and embed it with `tacks`

**Pull request closed without merging**
