### PR TITLE
Standard

### PR DESCRIPTION
**Pull request by sebdeckers**
Fixes some minor syntax warnings. :see_no_evil:

### CODE REVIEW

**Comment by cbas** [comment]
Build only fails in Node 0.8 ... but is this related at all to the style change?
https://travis-ci.org/npm/npm/jobs/85043844

(Still trying to get `npm test` to pass on my local machine. Somehow getting a few errors with node 4.1.2 on OSX 10.11 using the latest `master` branch. :sweat_smile: )

**Comment by iarna** [comment]
our build has failed on 0.8 for a long while now– ever since some of our testing related deps dropped 0.8 support =/

**Comment by cbas** [comment]
@iarna Thanks for clarifying. :smile: Hope this PR is good to merge then. I'm wondering though why `npm test` didn't pick up all these warnings when it also runs `standard`. I only found them by opening up the files with Atom's `linter-js-standard`.

**Comment by othiym23** [comment]
@cbas The version of `standard` that npm installs itself as a `devDependency` is an older one that doesn't complain about the issues you cleaned up (this leads to a confusing result if you have the latest `standard` globally installed but haven't run `npm install` against npm itself, because then when you run `npm test` it will produce errors, but won't after `npm install` is run). I was going to take on getting this cleaned up this week myself, so thank you so much for picking this up!

**Comment by cbas** [comment]
Ohh that explains it! Thanks :relieved: 

I've gone and bumped to the latest `standard@~5.3.1` and ran `standard --format` to fix the remaining files (mostly the `test/` folder). HTH.

**Comment by cbas** [comment]
@iarna @othiym23 Should I continue to keep this branch up to date with the latest pushes to master?

**Comment by iarna** [comment]
@cbas We'll take this during this week! If you can update it to match master that would be fantastic, but if not we'll take care of it.

**Comment by cbas** [comment]
@iarna :ok_hand: Updated.

**Comment by iarna** [comment]
Thank you! =)

**Comment by cbas** [comment]
Rebased the commits for your convenience. Thanks for the tip @timoxley

**Comment by iarna** [comment]
Good news and thank you for all this work, this landed in 3.3.10!

**Pull request closed without merging**
