### PR TITLE
put auto-pruning feature behind --no-auto-prune or auto-prune config setting

### PR DESCRIPTION
**Pull request by ghost**
This patch adds an `auto-prune` configuration setting that when set to `false` (either through `--no-auto-prune` or `npm config set auto-prune false`) disables the removal of unused packages.

The motivating use-cases for this patch are documented in this issue: https://github.com/npm/npm/issues/16853

Related no-delete-symlinks feature: https://github.com/npm/npm/pull/18922

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
awesome, thank you!

**Comment by fstoerkle** [comment]
@substack looking at the Travis CI build, I guess you need to add a default for this new option in https://github.com/npm/npm/blob/latest/lib/config/defaults.js

**Comment by ghost** [comment]
The build failed on node 6 because it timed out. It looks like an infrastructure problem in travis-ci not something related to this patch.

**Comment by darkobits** [comment]
Thank you for this, @substack! 😻

**Comment by heikomat** [comment]
This does indeed fix a lot of problems people are having with npm5, that did not exist on npm4! Thank you @substack!

**Comment by metasansana** [comment]
Is this likely to get merged? Honestly this auto pruning thing and issues with local installs are killing what was otherwise a pleasant development experience with npm.

**Comment by AndreiShostik** [comment]
guys, please, review.
it turned into a very annoying thing to come up with workarounds to return back symlinks

**Comment by zkat** [comment]
See my response over at https://github.com/npm/npm/pull/18922

**Comment by ljharb** [comment]
@zkat even with a lockfile i don’t want the pruning behavior; it breaks anything i set up in a postinstall script, links or not. It’d be really great to get this merged.

**Comment by zkat** [comment]
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

**Pull request closed without merging**
