### PR TITLE
support node 9, also update CI

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@MylesBorins looks like node 9 doesn't pass the build

**Comment by chrmoritz** [comment]
That's because https://github.com/npm/npm/commit/4ca6958196ae41cef179473e3f7dbed9df9a32f1 is required for node 9 support too (and this commit is only available in npmc canary atm, targeting the release-next branch instead of latest should work too).

**Comment by graingert** [comment]
Ok will try that.

**Comment by ilovezfs** [comment]
What's the status here?

**Comment by graingert** [comment]
@ilovezfs see https://github.com/npm/npm/pull/18964

**Comment by ilovezfs** [comment]
:tada:

**Pull request closed without merging**
