### PR TITLE
Installing dev dependencies updates npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by doug-wade**
Fix https://github.com/npm/npm/issues/11735

### CODE REVIEW

**Comment by doug-wade** [comment]
I'd kinda prefer to have a test for this, but as best I can tell, none of the existing install tests verify the behavior of npm-shrinkwrap.json, and I'm not entirely sure how I should structure them.  Should I add a new test class, something like test/tap/install-save-dev-with-shrinkwrapped-dev-deps-adds-new-dep.js in which I:

1.) set up a new package
2.) install a dep and a dev dep
3.) shrinkwrap
4.) install --save-dev other-dev-dep@version
5.) verify npm-shrinkwrap.json contains other-dev-dep at version

Or are we okay with saying that since there aren't tests for install's effects on npm-shrinkwrap.json or install --save-dev, that the community (me) shouldn't be setting precedent on how to test those?

**Comment by sheepsteak** [comment]
I made the original #11735 issue last week and had chance to look at this over the weekend too. I also tracked it down to that line but also noticed some edge cases.

If you do the following with your fix:
1. `npm init`
2. `npm i -S is-object`
3. `npm shrinkwrap --dev`
4. `npm i -D is-array`

You'll notice the shrinkwrap doesn't add `is-array` even though you specified `--dev`. This is because there's nothing in the shrinkwrap to tell npm what the original intent was and because it can't see any current devDependencies in there.

I guess the drastic solution would be to add an extra key to the shrinkwrap stating what the original user intent was but that's going to only be forward compatible and I have no idea how older npm will handle it. But the short-term solution might be to output a message when someone does `npm shrinkwrap --dev` but with **no** devDependencies that they need to do it again after installing their first devDependency.

Not sure if this should be another issue though as this PR does fix the original issue :)

**Comment by iarna** [comment]
@doug-wade I too would love to see tests for this. Our test coverage is still sketchy, so some features are currently just missing. Tests are everyone's responsibilty, so the cli team LOVES community provided tests. =)

I would do as you describe, create a new test script (and those series of steps sound reasonable to me).

Further testing hints:

1. You'll find that `npm-registry-mock` provides a handful of modules that are installable.
2. For setting up your initial environment, `tacks` aims to make this easier, see `test/tap/install-report-just-installed.js` for an example of its usage.

**Comment by Bockit** [comment]
Would it make sense for the key live in package.json?

**Comment by michaelnisi** [comment]
@doug-wade In step 3.) of your test outline, you mean `npm shrinkwrap --dev`, right?

**Comment by michaelnisi** [comment]
@iarna Maybe a new flag isn't needed. `npm shrinkwrap --dev` could add an empty `'devDependencies'` array to `npm-shrinkwrap.json` to remember user intent in later dev dep installs.

**Comment by michaelnisi** [comment]
@doug-wade If you don't mind, I'd start writing tests for this.

**Comment by iarna** [comment]
@michaelnisi Something along those lines is what I was thinking, yes. I wouldn't do it as an array, however. Just a boolean in the `npm-shrinkwrap.json`.

**Comment by iarna** [comment]
This is a thiiiing now! (That is, this PR is obsolete 'cause we implemented it.)

**Pull request closed without merging**
