### PR TITLE
remove sorting all of package.json

### PR DESCRIPTION
**Pull request by Qix-**
As per a discussion at chalk/ansi-styles#13, NPM shouldn't automatically sort `package.json` contents. It makes `--save` and `--save-dev` incredibly useless for collaborators on open source projects, making diffs annoyingly complex and invalidating thought-out and precise ordering of `package.json` elements (yes, some people are just _that_ anal-retentive about things).

Further, it doesn't seem to provide any real benefit to begin with.

This PR removes the two places in code where `package.json` is deep-sorted, and removes the deep-sort code itself since these two places are the only locations its used. ~~Further, it removes the test that checks for a sorted package.~~ It introduces a new sort function using the originally included `sorted-object` package (still net 0 added dependencies) that simply sorts dependency fields. Tests only appeared to check dependencies anyway - it looks like this PR fixes the _originally intended_ functionality.

I can confirm the failed test `test/tap/bin.js` is not a regression; it was present as of b3c0e86662a1f64132d42df81019e1fbec9d6846.

Docs don't seem to mention `package.json` sorting, so nothing to be changed there (let me know if this isn't true).

// @sindresorhus

### CODE REVIEW

**Comment by sindresorhus** [comment]
It should only sort the dependencies objects (dependencies, devDependencies, etc), not the other fields.

**Comment by Qix-** [comment]
Fixing now.

**Comment by KenanY** [comment]
@Qix- Are you using `npm@3`? Looks to me like https://github.com/npm/npm/commit/2f3c83a59f7387cff41ee0894707d1cffed04825 introduced this.

**Comment by Qix-** [comment]
@KenanY I am.

**Comment by othiym23** [comment]
@Qix-: can you help me understand how npm/npm#5779 is related? As far as I can tell, it only deals with shrinkwrap files, and not `package.json`. As much as possible, we try to treat shrinkwrap files as generated artifacts, which is at least a little different from how we think about / manage `package.json`.

@iarna what was your original intention with 2f3c83a59f7387cff41ee0894707d1cffed04825. Was it indeed just to make sure that the various dependency sections were alphabetized, or was there an intention to make the whole `package.json` file more consistent?

**Comment by Qix-** [comment]
@othiym23 that is the issue referenced by the commit that introduced the sort-everything functionality. :)

**Comment by iarna** [comment]
huh, I thought I had taken that back out, but apparently not…

**Comment by iarna** [comment]
1b71c55 is the actual commit responsible for current package.json sorting behavior

**Comment by iarna** [comment]
Ok, I'm gonna reject this PR, but thanks for raising this issue.

`install/update-package-json.js` is used to update `package.json` files IN your node_modules folders. Those are not user editable artifacts. It's behavior is correct.

By contrast `install/save.js` is for saving YOUR `package.json` and reasonably shouldn't be reshuffling unrelated keys on you.

**Comment by Qix-** [comment]
Great thanks @iarna

**Pull request closed without merging**
