### PR TITLE
view: always use arrays for versions, maintainers, etc.

### PR DESCRIPTION
**Pull request by kenany**
https://github.com/npm/npm/pull/7758 but rebased onto `multi-stage`.

> For consistency.
> 
> Fixes https://github.com/npm/npm/issues/7757

### CODE REVIEW

**Comment by iarna** [comment]
I rebase `multi-stage` on to npm@master every Friday, so there's no need to do pull request for things being merged into master.

**Comment by KenanY** [comment]
@iarna But we [don't want this](https://github.com/npm/npm/pull/7758#issuecomment-86852828) merged into `master`?

**Comment by othiym23** [comment]
But @iarna, I asked him to make this change against `multi-stage`, because I don't want it going into `npm@2` because it's a breaking change. :cry:

**Comment by KenanY** [comment]
FWIW, in preparation for this probably being re-opened, I've rebased against `multi-stage` after Friday's merges. I guess GitHub won't update the UI here since this has been closed.

**Comment by iarna** [comment]
Ah, I seee…

**Comment by iarna** [comment]
Cherrypicked as: b927723880bba882bd0df9148b31e2bd3387e7a4

**Pull request closed without merging**
