### PR TITLE
Fixed bug in unsupported.js

### PR DESCRIPTION
**Pull request by jayluxferro**
Changed ``  ` `` to  ``'``.

### CODE REVIEW

**Comment by kenany** [comment]
Can you please explain what bug this fixes?

**Comment by stephnr** [comment]
@jayluxferro that string is a templated string. Switching it to single quotes will prevent the variable `rel.min` from being added to the string.

**Comment by nwoltman** [comment]
Duplicate of #18953.

**Comment by zkat** [comment]
Closing as duplicate of #18953 -- also, this patch as-is would... not do what it's supposed to. Thanks for sending it in, though!

**Pull request closed without merging**
