### PR TITLE
Outdated Request Package - package.json

### PR DESCRIPTION
**Pull request by knoxcard**

### CODE REVIEW

**Comment by kenany** [comment]
What's the reasoning for this? Also note that you will have to update `package-lock.json` and `node_modules/` as well.

**Comment by knoxcard** [comment]
There were major fixes done in regards to the request package in the last 14 days....prior to that, wasn't updated since September 2017.
https://github.com/request/request/releases

Doing a simple npm update would result in warning messages stating these facts.  With request being a core function of Node, it could be detrimental in terms of performance and/or security, if one falls behind.

**Comment by knoxcard** [comment]
Notice the last 14 days, 4 updates....prior to that, it wasn't touched since September 2017.

https://github.com/request/request/releases

**Comment by evan-scott-zocdoc** [comment]
Isn't this equivalent to just doing `^2.0.0`?

**Comment by iarna** [comment]
I think the original concerns in this PR are resolved by this commit.

01e4e29bc request@2.85.0 (Rebecca Turner on 2018-03-22)

As such I'm gonna close this. If you'd like to discuss it more I encourage you to drop by #js-npm on the https://package.community/ Discord.

**Pull request closed without merging**
