### PR TITLE
Make "JSON" snippets valid JSON

### PR DESCRIPTION
**Pull request by s100**
Documentation for `package.json` [states](https://docs.npmjs.com/files/package.json) that it "must be actual JSON, not just a JavaScript object literal".

### CODE REVIEW

**Comment by iarna** [comment]
This looks good to me

**Comment by zkat** [comment]
This was merged and included in npm@3.7.0 and npm@2.14.17. Thanks!

**Comment by robludwig** [comment]
This is still not valid JSON, the versions field in lines 47-57 is an array but uses curly object braces instead of angled array brackets.

**Comment by s100** [comment]
Well, whoops.

**Pull request closed without merging**
