### PR TITLE
node-gyp@3.6.1

### PR DESCRIPTION
**Pull request by addaleax**
Basically ran `npm i -S node-gyp@3.6.1`, seems to have worked out well.

### CODE REVIEW

**Comment by zkat** [comment]
@addaleax Thanks! This is a release week, so we'll pull this in and send up a PR probably ~friday

**Comment by addaleax** [comment]
Cool! That isn’t npm@5 by any chance, is it? I hear it’s fast.

**Review by zkat — APPROVED** [review]
LGTM!

**Comment by zkat** [comment]
@addaleax we have a regular npm@4 release on top of the public beta for npm5. I hear it's fast too but it's probably all marketing bullshit tbh. Can't trust these corporate types imo.

New `node-gyp` should go into both :)

**Comment by zkat** [comment]
This has been included in npm@5.0.0. Closing

**Pull request closed without merging**
