### PR TITLE
support --save-peer

### PR DESCRIPTION
**Pull request by tkellen**
I think I covered everything here.  This adds support for installing things directly to `peerDependencies`.

### CODE REVIEW

**Comment by jcreamer898** [comment]
Since NPM 3 has a much greater need for peer dependencies now, seems like this would be a great feature... Thoughts @iarna?

**Comment by xpepermint** [comment]
+1

**Comment by QuantumInformation** [comment]
+1

**Comment by dvonlehman** [comment]
+1

**Comment by darkxeno** [comment]
+1

**Comment by gajus** [comment]
Yes, @iarna can you please take a look into merging this?

**Comment by capaj** [comment]
I too would appreciate if this was merged.

**Comment by shellscape** [comment]
bummed at the lack of traction on this one. sad panda.

**Comment by ffxsam** [comment]
Let's get this ball rolling again, shall we?

**Comment by jvivs** [comment]
PR #3995 has relevant discussion, but was closed and redirected to the [roadmap](https://github.com/npm/npm/wiki/Roadmap). Alas, whatever was there was removed and is being rewritten as of Jan 27, 2017.

Given the frequency of interacting w/ `peerDependencies` when working with `react`, it'd be great to know where the cli team stands and what the plans are to improve cli interactions w/ peerDeps (if any).

👍

**Comment by fearphage** [comment]
I don't see why you wouldn't want to install it.

> if you do npm install x --save-peer in /path/to/foo, where should x go to be a peer of foo? foo isn't even located in node_modules, so there's no reasonable place to put x.

It should go into `node_modules` like everything else. Peer dependencies mean that my script is going to call `require(x)` so make sure `x` is accessible. Installing in `node_modules` (like everything else) satisfies the role of a peer dependency as far as I can tell.

**Pull request closed without merging**
