### PR TITLE
Inflate nested dependencies within a shrinkwrap

### PR DESCRIPTION
**Pull request by misterbyrne**
Seems to fix https://github.com/npm/npm/issues/12372

### CODE REVIEW

**Comment by iarna** [comment]
This change looks good to me, but it's going to need a test.

**Comment by misterbyrne** [comment]
Cool! I've already included a test - which fails without my change and passes with the change. I'm not sure whether you mean that you would prefer my test to be extracted into its own file, whether you would prefer a unit test rather than an integration test. Or something else :/

**Comment by iarna** [comment]
So you did! I don't know how I overlooked that!

**Comment by iarna** [comment]
I think I may rewrite it to be a separate test file (as I think it's outside of the scope of the existing file) but I'm happy to do that as part of landing this.

**Comment by misterbyrne** [comment]
Cool - Thanks! - I'm pretty excited about this one! 😄

**Comment by misterbyrne** [comment]
https://github.com/npm/npm/issues/12702 😞

**Comment by iarna** [comment]
This was merged in 3.9.0– I'll see if I can't do another small patch release this week for #12702.

**Pull request closed without merging**
