### PR TITLE
cache: fix several addLocal-related race conditions

### PR DESCRIPTION
**Pull request by zkat**
Look, if we know we can't chownr, then let's just not chownr, jfc

### CODE REVIEW

**Comment by iarna** [comment]
Testing this will involve injecting `getCacheStat` to ensure that it returns a value without uid or gid & injecting `chownr` to ensure that it's not called.

**Comment by othiym23** [comment]
LGTM! :sheep::rocket::fire:

**Comment by zkat** [comment]
This fix needs to be backported and tested on LTS

**Comment by zkat** [comment]
This was merged into mainline with `npm@3.10.4`. It still needs backporting to LTS, so I'm gonna leave this open until then.

**Comment by zkat** [comment]
This was merged into the LTS branch and will go into whatever that next release is when it happens. In the meantime, I'm closing this.

**Comment by zkat** [comment]
reopening until https://github.com/npm/npm/pull/13362 is merged

**Comment by iarna** [comment]
Closing as the merge of #13362 is planned for later today. Plus closing things is how I'm tracking them. =)

**Comment by speigg** [comment]
@iarna I hope this fixes #13619 :)

**Pull request closed without merging**
