### PR TITLE
WIP: add --time-machine option (only install deps released on or before a given date)

### PR DESCRIPTION
**Pull request by jedwards1211**
See https://github.com/npm/npm/issues/12994

I'm absolutely sure this will need tests and more work, I'm putting it up now to get feedback.

With these changes I was able to get back a set of working deps and subdeps in my project and create the necessary `npm-shrinkwrap.json` for them.  Yay!

Right now I just filter the versions that `fetchPackageMetadata` and `addNamedRange` take into consideration.  Are there other parts of the code looking at package versions where I need to filter out the ones after the time machine date?

### CODE REVIEW

**Comment by SimenB** [comment]
Oh, yes please! Awesome feature.

Would have saved me so much time at one point. Going between a machine with working output, and my own which did not, and comparing output of `npm ls` was annoying. At least we had a working version, so in the end we just generated a shrinkwrap file on his machine, but if we did not have a machine with a working setup, this would have saved us.

**Comment by jedwards1211** [comment]
@SimenB exactly, I had lost a *working* copy, and I thought, wait a minute, if I did a fresh `npm install` a week or two ago, I would get a working project, so why can't I do that now?

**Comment by jedwards1211** [comment]
I'm guessing I probably shouldn't be handling the `--time-machine` option directly in `fetchPackageMetadata` and `addNamedRange` unless we can verify that it works properly with any `npm` command; to make it work only on `npm install`, I could have those functions use a differently-named field in `npm.config` that only `install.js` copies from `--time-machine`.

Would you guys prefer `--ignore-versions-after` for the argument name?

**Comment by jedwards1211** [comment]
@SimenB I noticed in the roadmap that the npm team wants to achieve consistent installs, i.e. `npm install` always does the same thing if the deps haven't changed.  I'm guessing a solution to this problem that doesn't require time machine is possible then.

For instance: perhaps when installing a version of a package, `npm` should ignore subdep versions that were released after that version of the primary package was released (unless the subdep versions are in the shrinkwrap).  This would fail to get minor bugfixes on transitive deps, but if those are needed, one could then install later versions of those transitive deps and create a shrinkwrap.

**Comment by SimenB** [comment]
I don't know if I'd like that as default behavior, I'd expect a fresh `npm install` to install newest semver compatible of all packages. If I want by some date, this option seems fair.

`ignore-versions-after` is probably a better name, more self-explanatory.

**Comment by jedwards1211** [comment]
@SimenB maybe a `--reproducible` option for the per-subdep date restrictions I described above?

**Comment by zetlen** [comment]
This would combine wonderfully with a bisecting utility.

**Comment by jedwards1211** [comment]
@zetlen look who it is, I met you at Volusion!
What do you mean by bisecting?

**Comment by SimenB** [comment]
Probably something like #7160

**Comment by zetlen** [comment]
Oh hey @jedwards1211. Yeah, I mean a utility like `git bisect`, that starts from a broken state, zooms back to a known-good state, and binary searches the intermediate states for the breaking change. This feature wouldn't give you every possible intermediate state, but it would let you determine a smaller time window, and then we could do the expensive work of making and searching a complete set of tree states by sorting nodes on last release date. I expect this probably runs pretty slowly, but at least it runs by itself!

**Comment by jedwards1211** [comment]
Ah, very cool, that would be neat.  At least that process could be parallelized, even though it would be pretty resource intensive.

**Comment by jedwards1211** [comment]
@SimenB I agree that `--ignore-versions-after` would be a good name for the option

**Comment by jedwards1211** [comment]
Hmmm, on my machine this seems to think no version is found unless you specify a specific version.

**Comment by SimenB** [comment]
Any news here 😄

**Comment by jedwards1211** [comment]
@SimenB I think they probably won't touch it again unless I implement tests and get CI to pass.  Which sadly I don't have time for right now, especially given how complicated testing it would be...

**Comment by iarna** [comment]
We're closing this pull request as it has gone sixty days without activity.  In our experience pull requests that go this long are unlikely to land.  If you have updates to it, please feel free to open a new pull request.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).

**Pull request closed without merging**
