### PR TITLE
Add flag to force `update` to install latest version

### PR DESCRIPTION
**Pull request by refack**
But only in "our" package's modules (not recursively, cause that's just crazy ;-p )

### CODE REVIEW

**Comment by smikes** [comment]
How about this:

```
npm --depth 0 outdated
npm --depth 0 update --save
```

The first command will list what's about to happen; the second command will try to update all the direct dependencies to `@latest`, honoring semver.

**Comment by othiym23** [comment]
Why is `--depth 0` necessary in either case? Is this presuming a pre-`npm@2.6.1` world?

**Comment by smikes** [comment]
Yes, at present I am assuming that at best people are running npm@latest, not npm@next

Also even with npm@2.6.1 once when I did update --dev --save-dev the behavior looked suspiciously like an infinite loop.

**Comment by othiym23** [comment]
A lot has changed around `npm outdated` and `npm update` recently, and I don't think this patch makes sense. @smikes, if you (or somebody else!) want to put together a patch to make

```
npm outdated
npm update --save
npm update --save-dev
```

work the way you describe above, that would have my support / get merged quickly.

@refack, I apologize for the lengthy delay between you submitting this patch and us reviewing it, and I also apologize that all that time went by only for me to decide not to merge it. Thanks for taking the time and energy to put this together!

**Pull request closed without merging**
