### PR TITLE
Fix unreadable text in `npm outdated` using solarized dark theme

### LINKED ISSUE #12842: NPM outdated 'dir' column unreadable with solarized dark theme
I didn't even realize there was anything in the Location column until I accidentally highlighted:

screen shot 2016-05-25 at 5 37 52 pm

I vote we complete the color wheel triad with cyan:

screen shot 2016-05-25 at 5 39 23 pm

### PR DESCRIPTION
**Pull request by tribou**
Fixes #12842

### CODE REVIEW

**Comment by othiym23** [comment]
This isn't something we can test in an automated way, so somebody is going to need to eyeball this in a variety of terminals / a variety of OSes to ensure that making this change doesn't cause problems for somebody _else_.

**Comment by zkat** [comment]
Because any particular color usage is potentially problematic across terminals, and in the interest of not needing to do all these manual tests and guaranteeing maximum readability, it might be better off to simply omit these two color settings altogether: The column doesn't really need any color coding and doesn't really gain anything from setting any color. By not setting a color, it will simply use the default text color, which will be the same one used for the `Current` column, which we already assume works reasonably well. How about that change?

**Comment by tribou** [comment]
Sure, that works well for me.  Here's the updated look on solarized dark:

screen shot 2016-06-01 at 9 42 11 pm

**Comment by iarna** [comment]
LGTM! I'm adding this to this weeks release.

**Comment by iarna** [comment]
Landed in 3.10.0!

**Pull request closed without merging**
