### PR TITLE
candidate implementation of async tmpdir cleanup

### PR DESCRIPTION
**Pull request by smikes**
fixes issue #6855

### CODE REVIEW

**Comment by smikes** [comment]
/cc @othiym23 needs-review, candidate for #next-minor ?

Which is not to say that you should review it – perhaps one of your minions. :smirk_cat:

**Comment by othiym23** [comment]
As far as I know, you *are* one of my minions if anyone is, @smikes. I mean, it's just me and @iarna on the core team, and if either of us is a minion, we both are (of each other).

My considered, logical reaction is: I dunno about this. It fulfills the requirement of cleaning up after npm without slowing down its perceived responsiveness, but I have questions:

1. What happens with this when something goes wrong with the removal, for whatever reason? Because I/O is going into the bit bucket, we'll have no way of signaling to the user that something untoward occurred.
2. Windows. I know that's not a question, but detached processes are kind of scary on Windows, and if, say, rimraf hangs, there will be a wedged Node process hanging around that users might not think to look for.
3. Isn't that test at least a little racy? It doesn't / can't wait for the cleanup to complete before checking to see if the temp directory is gone, and this is exactly the sort of race condition heavily-loaded CI servers with spinning disks love to expose.
4. Isn't this a lot of complexity (a detached process, magical behavior) to add for something that should arguably be handled by the operating system? As I'll comment over on #6855, @isaacs and I have talked it through, and neither of us are convinced that npm is being any more prolific in creating temporary directories now than it was in the past. Installations are growing ever more complex, it's true, but this is not a thing that is specific to npm – CI servers and the like should be running `tmpwatch` with a pretty tight timeout.

**Comment by smikes** [comment]
I say kill it with one caveat: can we put in a thought about this wrt npm@3, such that git repository dependencies get sorted earlier in the process, and we add an async cleanup of tmpdir into the mix?  Realistically an async rimraf of a /tmp git repo could be fired off as soon as we know we don't need it anymore, i.e., as soon as the git-clone-to-cache completes.

**Comment by othiym23** [comment]
> an async rimraf of a /tmp git repo could be fired off as soon as we know we don't need it anymore

This is a valuable insight, and one you should go add on to #6855. I don't think this needs to wait until `npm@3` to be implemented, either (although it might be convenient for @iarna to do that work against the `multi-stage` branch so she doesn't have to merge it in) – this is a self-contained feature that can land pretty much whenever.

Since we both agree in principle that this is no bueno, I'm going to close it now. Thanks for the time you put into it, Sam!

**Pull request closed without merging**
