### PR TITLE
README: fix typo

### PR DESCRIPTION
**Pull request by strugee**
https://twitter.com/izs says he/him, so I assume "she" in the README is a typo? Feel free to close if not. /cc @isaacs

### CODE REVIEW

**Comment by kenany** [comment]
Maybe this was intentional? https://github.com/npm/npm/commit/9c663b2dd8552f892dc0205330bbc73a484ecd81#diff-04c6e90faac2675aa89e2176d2eec7d8R159

**Comment by strugee** [comment]
@KenanY yeah, I saw that. I can't really tell (the commit message doesn't mention it at all) so I figured I'd open this just in case

**Comment by iarna** [comment]
tbh we probably shouldn't be telling anyone to look for isaacs at all, seeing as he isn't actually involved here day-to-day now.

**Comment by strugee** [comment]
@iarna does the npm team even want to do support/issues through IRC anymore? If so I'm happy to amend to change the nick referenced in this section, but otherwise it seems like we should probably just nuke this section

**Comment by zkat** [comment]
No, tbh I never check IRC and I'd rather people contact us either through the issue tracker, or through the `#npm` channel in https://package.community, or through Twitter.

I'm gonna close this particular PR and welcome a new one rewording things accordingly! 💯

**Pull request closed without merging**
