### PR TITLE
npm: remove some ancient aliases

### PR DESCRIPTION
**Pull request by zkat**
this was brought to my attention, and I really don't feel great having these aliases.

### CODE REVIEW

**Comment by backspace** [comment]
Thank youuuu 💞

**Comment by othiym23** [comment]
Rubber-stamp LGTM. :sheep::rocket::fire:

**Comment by iamstarkov** [comment]
where are the files/commits from pull-request to code-review? github states 0/0

**Comment by backspace** [comment]
@iamstarkov: 	643dae2

**Comment by iamstarkov** [comment]
@backspace thank you

**Comment by panuhorsmalahti** [comment]
To save some clicks: the unacceptable aliases were 'gangster' and 'gangsta'.

**Pull request closed without merging**
