### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ifdattic**

### CODE REVIEW

**Comment by othiym23** [comment]
Halfway there! `npm_config_binroot` is actually correct, though, so that part shouldn't be changed.

**Comment by othiym23** [comment]
Note: needs to be landed on both `2.x` and master.

**Comment by othiym23** [comment]
Rebased, squashed, and landed as 7cf63662e0d93d7a6be3b0bc57a141284144371c on `release-3.4.0` and 16361d122f2ff6d1a4729c66153b7c24c698fd19 on `release-2.14.10`. Thanks for putting this together!

**Comment by ifdattic** [comment]
Glad to help!

**Pull request closed without merging**
