### PR TITLE
inflate-shrinkwrap: allow fakeChildren for non-integrity types

### PR DESCRIPTION
**Pull request by zkat**
Fixes the case helpfully described in https://gist.github.com/jmorrell/057caf31563a95c7c9c880867afcfea3

/cc @jmorrell

### CODE REVIEW

**Comment by jmorrell** [comment]
Oh yay! Thank you for taking a look at this :)

**Comment by zkat** [comment]
@jmorrell thanks so much for the excellent repro. It was really easy to figure out what was going on (and whether I'd fixed it) because I was able to check what exactly you were running into, in context. Seriously, thanks ^_^

**Review by iarna — APPROVED** [review]

**Comment by iarna** [comment]
Looks good—we definitely should be constructing fake children for any entry that matches what we produce, at the very least.

**Comment by zkat** [comment]
Note: I'm gonna hold off on merging this. It's making some of our tests fail (probably because they weren't written expecting to take the fakeChild code path), so it'll have to go in next release.

**Comment by iarna** [comment]
Landed in 6.0.0!

**Pull request closed without merging**
