### PR TITLE
version: allow scripts to add files to the commit

### LINKED ISSUE #8620: allow `preversion` and `version` scripts to add files to the commit
The `git version` command is useful if all you need to do is bump the value in package.json. If you try to generate/compile any files as part of your release process, then it complains:

```
npm ERR! Error: Git working directory not clean.
```

I think it should work (something) like this

  1. Check to make sure the git working directory is clean before running any scripts (scripts in future steps may add files to the commit without throwing an error).
  2. Run the `preversion` script. These scripts have access to the old `version` in package.json. Any files you want added to the commit should be explicitly added using `git add`.
  3. Bump `version` in `package.json`. 
  4. Run the `version` script. Scripts here have access to the new `version` in package.json (so they can incorporate it into file headers in generated files for example). Again, scripts should explicitly add files using `git add`.
  5. Commit and tag
  6. Run the `postversion` script.

The most important part is being able to easily incorporate generated files as part of the commit that will be tagged, and easy access to what that version number was / will be.

### PR DESCRIPTION
**Pull request by jamestalmage**
Closes #8620

### CODE REVIEW

**Comment by jasonkarns** [comment]
Is it necessary that the working directory actually be clean before proceeding? As a user, if I didn't have any `preversion` or `version` scripts, I wouldn't feel it necessary to ensure a clean working directory just to bump my package version. Instead of checking for clean working directory, perhaps all that should be checked is the index? Since modified files won't be committed unless explicitly added by scripts, I would think that a clean index is all that should be ensured prior to running `version`.

**Comment by jamestalmage** [comment]
Hmm,
That test passed on my machine. I'll keep working on it.

**Comment by jasonkarns** [comment]
<moved my comment to the issue thread instead of this PR>

**Comment by jamestalmage** [comment]
OK,
Here is the error:

```
  Error: Command failed: git commit -m 0.0.1  
        *** Please tell me who you are
        Run
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
```

Not sure how the other tests are getting around this, looking into it.

**Comment by othiym23** [comment]
@jamestalmage take a look at https://github.com/npm/npm/blob/master/test/common-tap.js#L61, which I think will be useful for you in your tests. I have thoughts on the rest of this PR and #8620, but I may not have time to get to them today. This should get you unblocked in the meantime.

**Comment by jamestalmage** [comment]
I think I got it already

**Comment by jamestalmage** [comment]
@othiym23 
I look forward to your input. Yesterday afternoon was my first time poking around inside the npm codebase, and I am pretty sure I have seen `< 1%` of it. The chances that I am missing the "right way" to do things are high, so pointers are welcome.

I am going to hold off on any changes discussed in the #8620 thread until I hear from you (happy to make the changes, just want them blessed by a collaborator first).

**Comment by jamestalmage** [comment]
@othiym23 
`--force` flag added and ready for your input.

Do you want me to squash now or after your review?

**Comment by jamestalmage** [comment]
Holy major freakin upstream commits! I certainly picked the exact wrong day to work on a PR!

Lint errors are fixed, but I'm still getting some weird errors locally:

screenshot 2015-06-26 00 10 00

I don't think I caused that.

**Comment by jamestalmage** [comment]
@othiym23 
What's with the `update AUTHORS` commit? I'm guessing I ran some command I shouldn't have. I can rebase it out if necessary.

**Comment by jamestalmage** [comment]
Also,
It doesn't appear Travis is producing the same failures from my screenshot above. Advice on how to get those tests working locally would be appreciated.

**Comment by iarna** [comment]
@jamestalmage npm has a hook for the version command so I imagine you probably ran `npm version` at some point in your npm checkout while you were testing... and off it went.

**Comment by jamestalmage** [comment]
ahh, yes. `package.json` did have a version bump, but I caught that.

**Comment by jamestalmage** [comment]
OK,
Travis only failed on node `0.8`, and it looks like that's happening to everybody.

**Comment by othiym23** [comment]
We have a ways to go to get the whole test suite passing on Travis – npm's tests drive the system pretty hard, and there are a lot of versions of Node.js and io.js that npm needs to support. As long as the tests pass for you locally, don't worry about it.

**Comment by othiym23** [comment]
(Although we are slowly and painfully working on making the test suite more robust under Travis.)

**Comment by jamestalmage** [comment]
Hmmm,
I should have squashed before I merged. 
My initial commits (from yesterday!!) are now some 100 lines back in the logs.

I'll say it again. I picked the wrong day...

What should I do here. Trying to rebase that far back sounds painful.

**Comment by othiym23** [comment]
The easiest thing to do would be to pull down the `2.x` branch and then rebase on that, and then we can merge or cherry-pick off that branch onto `master`. `2.x` is basically the branch you started working against, and it should be an easy rebase.

If you want brownie points (and who doesn't?), check your patch against `standard` before giving us the thumbs up to review it again.

**Comment by jamestalmage** [comment]
It's already passing against standard.

Also, I've already fully merged the 3.0 branch (and it's passing tests and standard). But I did so halfway through, so I've got 4 commits before all the 3.0 stuff that is going to be difficult to squash into a single commit.

Basically, it's ready to go - but it pollutes your commit history more than it should.

**Comment by jamestalmage** [comment]
@othiym23 
Turned out to be pretty easy. I filed a separate PR against the 2.X branch. This branch is now simply a cherry-pick of that one (with some merge conflict resolution). Take your pick (pun fully intended).

**Comment by jasonkarns** [comment]
In the issue thread, @jamestalmage you mentioned that the `preversion` script will have access to the old `version` and the `version`/`postversion` scripts will have the new `version` value. How is that value referenced? Via `$npm_package_version`? Or other global var? Or script parameter?

I ask because I just recently discovered that `$npm_package_version` isn't kept up to date during the `version` lifecycle. It's read at `preversion` and remains unchanged throughout the lifecycle.

**Comment by jamestalmage** [comment]
It's written back to `package.json` before those scripts run.
Setting the environment variable shouldn't be too difficult.

@othiym23 any reason **not** to do that?

**Comment by jasonkarns** [comment]
gotcha. So the expected use is to read in package.json again in the version/postversion scripts...

Updating `$npm_package_version` during the lifecycle probably ought to be a separate PR from this, I imagine?

**Comment by jamestalmage** [comment]
@jasonkarns yeah - I would assume a separate PR.

@othiym23 Unless you want the environment variable updated as part of this PR, this should be ready for review.

**Comment by iarna** [comment]
Landed in master as 21ce8fe

**Pull request closed without merging**
