### PR TITLE
first draft of update examples

### PR DESCRIPTION
**Pull request by smikes**
ref issue #7417

### CODE REVIEW

**Comment by othiym23** [comment]
These are fantastic. Thank you very much for putting them together.

Have you confirmed that all the scenarios you describe work that way in practice?

**Comment by smikes** [comment]
How about a unit test?

**Comment by smikes** [comment]
Note that the unit test depends on 7477, if missing it fails with

```
$ tap test/tap/update-examples.js
/Users/smikes/src/github/npm/node_modules/npm-registry-mock/node_modules/hock/lib/hock.js:385
          throw new Error('No Match For: ' + req.method + ' ' + req.url);
                ^
Error: No Match For: GET /abbrev
```

**Comment by othiym23** [comment]
Tweaked a tiny bit (so tiny that you probably won't even spot it), rebased, and landed as 5bc70e6cfb3598da433806c6f447fc94c8e1d35d. This is excellent, Sam. Big thanks for putting it together.

**Pull request closed without merging**
