### PR TITLE
Ensure that 'npm cache ls' outputs actual filenames

### PR DESCRIPTION
**Pull request by isaacs**
Hi, cli team.  I don't know if there's a bug open for this already, but I noticed it the other day, and had a moment to write some code, so here you go :D

### CODE REVIEW

**Comment by iarna** [comment]
Hmm, this test passes w/o the patch so... I'm not actually clear on what the bug was to start with?

**Comment by iarna** [comment]
We have observed that `npm cache ls` can end up with a doubled up portion, which maybe this was meant to address. I'll double back and see if this doesn't fix that problem (and fix up the test if so).

**Comment by isaacs** [comment]
@iarna Weird!  The test definitely didn't pass on my system without the patch when I wrote it, but does pass now

The root problem still exists, though, so the test is probably just not reproducing it properly or something.

```
$ npm cache ls rimraf
~/.npm/rimraf/rimraf/
~/.npm/rimraf/rimraf/2.1.4/
~/.npm/rimraf/rimraf/2.1.4/package.tgz
~/.npm/rimraf/rimraf/2.1.4/package/
~/.npm/rimraf/rimraf/2.1.4/package/package.json
~/.npm/rimraf/rimraf/2.2.8/
~/.npm/rimraf/rimraf/2.2.8/package.tgz
~/.npm/rimraf/rimraf/2.2.8/package/
~/.npm/rimraf/rimraf/2.2.8/package/package.json
~/.npm/rimraf/rimraf/2.5.0/
~/.npm/rimraf/rimraf/2.5.0/package.tgz
~/.npm/rimraf/rimraf/2.5.0/package/
~/.npm/rimraf/rimraf/2.5.0/package/package.json
~/.npm/rimraf/rimraf/2.5.1/
~/.npm/rimraf/rimraf/2.5.1/package.tgz
~/.npm/rimraf/rimraf/2.5.1/package/
~/.npm/rimraf/rimraf/2.5.1/package/package.json
~/.npm/rimraf/rimraf/2.5.2/
~/.npm/rimraf/rimraf/2.5.2/package.tgz
~/.npm/rimraf/rimraf/2.5.2/package/
~/.npm/rimraf/rimraf/2.5.2/package/package.json

$ ls -laF ~/.npm/rimraf/rimraf/
ls: /Users/isaacs/.npm/rimraf/rimraf/: No such file or directory
```

**Comment by isaacs** [comment]
Updated test to fail on master properly.  It was only passing if no path arg was passed to cache ls.

**Comment by isaacs** [comment]
Travis fails are now only due to timeouts in Node 0.x.

**Comment by iarna** [comment]
This landed in 3.9.0 =)

**Pull request closed without merging**
