### PR TITLE
docs(readme): add coveralls badge pointing to latest branch

### PR DESCRIPTION
**Pull request by ninjasort**
#14415

### CODE REVIEW

**Comment by KenanY** [comment]
The change to the Travis badge would already be covered by https://github.com/npm/npm/pull/14426.

**Comment by cameronroe** [comment]
@KenanY Sure, so can you merge that first or delete it.

**Comment by KenanY** [comment]
@cameronroe I can't (or at least shouldn't, without approval from the rest of the team) merge PRs but sure I'll delete it if you'd like.

**Comment by zkat** [comment]
screen shot 2016-10-26 at 13 55 50 Seems neat!

**Comment by cameronroe** [comment]
Just curious. Why are so many PRs failing the build? Shouldn't the build be passing on this?

**Comment by zkat** [comment]
@cameronroe a mixture of our AppVeyor setup needing a bit of work, and a couple of Windows tests failing recently :\

**Comment by othiym23** [comment]
While it's interesting to see the current coverage of the CLI code base, I'm not going to take this pull request. This is because, in my judgment, I don't believe that advertising the coverage level is currently useful or actionable for the CLI's users. Coverage has been at around 85% pretty much since we finished fixing up the test suite to run under Travis, and that's not super great. This is even despite the fact that we have several thousand individual test cases in the test suite, and pretty extensive integration test coverage.

The team insists that new changes come with tests, even if writing them is fairly complex. This process frequently needs a lot of support from the team, because npm's internal architecture is unwieldy in a way that makes writing traditional unit tests difficult – you either have to do a significant amount of redesign of the relevant CLI code, or you end up having to do fairly tricksy mocking within the module cache. Also, as a CLI tool,  a lot of the tests are written to drive npm from the command line, which makes the test suite slow (and, because a lot of them end up doing similar things, makes it tough to safely parallelize tests, as you suggest in #14431).

Because writing good tests for npm requires an intimate familiarity with the CLI's internals, the core team pretty much needs to be in the loop to review any sizable changes to the test suite. Also, given the idiosyncrasies of the code base (which the team is working diligently to reduce over time), new tests need a certain amount of vetting to ensure that they're testing the right things. This makes improving the coverage of the test suite a slow, incremental process, and one that requires a lot of time and attention from the core contributors.

As a result, the coverage number is stubbornly slow to increase, and the project isn't in a place where we can really delegate to process of improving that coverage (which is not to say that the team wouldn't _tremendously_ appreciate it if contributors took the initiative to write the missing tests – we would :heart:love:heart: this, were it to happen). As such, having a crappy coverage number at the head of the README would be more of a discouraging reminder of how many different ways our time and attention are split right now more than any kind of encouragement. We do very much care about the direction the coverage arrow is pointing, but the actual number itself is less interesting / helpful right now.

Thanks for your time and attention, and please, if you are interested in helping us get the coverage number up, by all means contribute new tests! We're happy to work with you, time permitting, to understand the bits of the architecture that make it challenging to write tests, and we appreciate all help in making the code easier to test. See #14431 for more thoughts on switching test frameworks.

**Comment by cameronroe** [comment]
Hmm.. while I can understand where you're coming from, does it make sense to improve the [contributing docs](https://github.com/npm/npm/wiki/Contributing-Guidelines) surrounding testing? There's no real entry point for new developers.

> Use existing tests as a reference.

I also don't think adding coverage goes backwards in anyway, promotion of the actual test coverage is a good thing that drives action toward improving. It's also not terrible (~85%). If coverage isn't a concern, then why have it at all? It's either important, or not important.

If tests are hard to implement, then what are the ways to take the appropriate steps to reduce friction around adding them ?

**Comment by othiym23** [comment]
> If coverage isn't a concern, then why have it at all? It's either important, or not important.

It's important to the CLI team, but maybe not so important or relevant to people not on the team, is what I'm saying.

**Comment by othiym23** [comment]
As to the rest, improving the contributors' documentation is high on my list of things to do, but so are many other things. I'll try to get to that before the end of the year, if at all possible. It's absolutely important.

**Comment by cameronroe** [comment]
@othiym23 Sounds good. Happy to help where I can. Including #14431.

**Pull request closed without merging**
