### PR TITLE
candidate fix for #2556 `install --link` with git dependency goes to registry

### PR DESCRIPTION
**Pull request by smikes**
This is an attempt at a failing test for #2556 .  I say "attempt" because although I can get a failure on the command line with this setup, I can't make it fail programmatically.

When run on the command-line, `installOne` is going into the `localLink` branch, which causes the failure.

However in the attached unit test, `installOne` just succeeds without going into the link branch.

Output of a successful test run and a failed command-line run in this gist: https://gist.github.com/smikes/daf021d1eb588536bad5

### CODE REVIEW

**Comment by smikes** [comment]
Blocking: Sam needs to revisit this test, possibly add `prefix`, see if it would work to use same-process `npm.commands.foo` test instead of `common.npm([...])` subprocess test

Blocking: fix for underlying bug

**Comment by smikes** [comment]
Unblocked and ready for review.

**Comment by othiym23** [comment]
@iarna, I'd like your eyes on this one. The fix feels a little like a proximate fix rather something that addresses the underlying issue, but it works, according to this excellent test that @smikes wrote. This also looks like cheese that will need to be moved soon.

**Comment by iarna** [comment]
Yeah, I'll see how this interacts with multi-stage, since ALL THE CHEESE related to this moved.

**Comment by iarna** [comment]
A HAND MOVING ALL YOUR CHEESE – FOREVER

**Comment by smikes** [comment]
A shining red dot that you can never catch, forever

**Comment by smikes** [comment]
Even if the fix is junk, the test should be salvageable

**Comment by othiym23** [comment]
Well, if it's a proximate fix, I can still land it in `npm@2`, and @iarna can figure out how to land it (or not) for `npm@3` (and bring over the test, either way). I'll work on this now.

**Comment by othiym23** [comment]
Good news! I landed this! I had to make some tweaks, though – a few tests were failing due to the change's assumption that `_resolved` would always be set by that point in the installation process (in the case of regular semver ranges or `dist-tag`ged packages, it might not be). I switched it to use `_from`, and added a guard that would prevent it from exploding in those cases. It still feels a little hacky, but that's fine, because the affected code is gonna die soon anyway. Landed as c618eeda3e321fd454d77c476b53a0330f2344cc and 39032e745ef6f610f489d429292df350d556ccc7. Thanks, Sam!

**Pull request closed without merging**
