### PR TITLE
Relative local specifiers in a shrinkwrap should be relative to the shrinkwrap

### PR DESCRIPTION
**Pull request by iarna**
A bug was introduced in 3.9.0 with the npm-package-arg/realize-package-specifier change where they would be relative to the requiring module's source directory (if the requiring module was also a local dependency).

This fixes https://github.com/JamieMason/shrinkpack/issues/45

### CODE REVIEW

**Comment by zkat** [comment]
LGTM

**Comment by zkat** [comment]
@iarna this patch doesn't cleanly apply because of https://github.com/npm/npm/pull/13212 :\ I'm not exactly sure which `where` to keep, here.

**Comment by zkat** [comment]
I think I got it.

**Comment by iarna** [comment]
Landed in 3.10.4!

**Pull request closed without merging**
