### PR TITLE
Corrected the typo in package-locks docs - #17967

### PR DESCRIPTION
**Pull request by vikramnr**

### CODE REVIEW

**Comment by vikramnr** [comment]
@KenanY Any idea why this failed

**Comment by kenany** [comment]
@vikramnr Probably not your fault. I wouldn't worry about the CI for docs patches like this.

**Comment by iarna** [comment]
@vikramnr Seems to have failed due to problems at Travis.

**Comment by iarna** [comment]
Thanks! Landed as a4e431369 in `release-next`.

**Comment by vikramnr** [comment]
That's Great !!!

**Pull request closed without merging**
