### PR TITLE
fix "npm --depth 2 update"

### LINKED ISSUE #19107: `npm --depth 2 update` fails
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Running `npm --depth 2 update` stops prematurely with the error:

```
TypeError: Cannot read property 'filter' of undefined
```

#### How can the CLI team reproduce the problem?

1. `git clone https://github.com/aheckmann/npm-update-test`
2. `npm --registry=https://registry.npmjs.org/ install`
3. `npm --depth 2 --registry=https://registry.npmjs.org/ update`

Debug log: https://gist.github.com/aheckmann/91b9adb3c8b7f0e232e745ef7c898367

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: 4.8.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Relates to https://github.com/npm/npm/issues/19045

### PR DESCRIPTION
**Pull request by aheckmann**
fixes #19107 

Still needs a test but I can prove it's working using: https://github.com/aheckmann/npm-update-test

Steps to see this working:

1. git clone https://github.com/aheckmann/npm-update-test
1. npm --registry=https://registry.npmjs.org/ install
1. npm --depth 2 --registry=https://registry.npmjs.org/ update

### CODE REVIEW

**Review by iarna — COMMENTED** [review]
Thanks for finding this!

It's interesting to note that for my various test repositories, this doesn't reproduce, so your reproducer is super helpful!

I'm happy to turn that into a test, but I'm gonna take a crack at figuring out why those properties aren't getting set as it's probably symptomatic of a deeper bug.

**Comment by aheckmann** [comment]
Thanks @iarna. From what I could tell, those properties may be missed [here](https://github.com/aheckmann/npm/blob/8b5f7ac980e7667f8eec1692ca2be3d0439b5f6b/lib/outdated.js#L214-L219) and [here](https://github.com/aheckmann/npm/blob/8b5f7ac980e7667f8eec1692ca2be3d0439b5f6b/lib/outdated.js#L235-L239). Though changing these lines also seems to fix the symptom, I'm not confident enough with this codebase to know for sure that there were no other sources of missing properties, hence the single catch all approach in this PR.

**Review by andelmad — APPROVED** [review]

**Comment by thom-nic** [comment]
Is there anything holding up this merge?  I'm stuck trying to upgrade some deep transitive dependencies (`via npm update --depth`) that NSP is flagging as vulnerable.  For some reason, even if I totally remove the top-level package and re-add it, it doesn't use the latest dependency version that it should given the version spec in package.json.

**Comment by hypery2k** [comment]
will this PR merged and added in npm@5 ?

**Comment by legodude17** [comment]
@hypery2k I doubt it, given that npm@6 has been released.

**Comment by zkat** [comment]
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

**Pull request closed without merging**
