### PR TITLE
doc: fix html charset declaration

### PR DESCRIPTION
**Pull request by kenany**
Fixes: https://github.com/npm/npm/issues/13225

### CODE REVIEW

**Comment by iarna** [comment]
Landed in 3.10.6!

**Comment by othiym23** [comment]
@KenanY could you do the CLI team a favor and not shortcut the triage process by attaching labels to issues / PRs before the team has a chance to run it through our process? Thanks!

**Comment by KenanY** [comment]
@othiym23 Of course!

**Comment by iarna** [comment]
This is merged into the lts release branch and will be in the next release (scheduled for later today).

**Pull request closed without merging**
