### PR TITLE
lib: Add sign-git-commit config

### PR DESCRIPTION
**Pull request by tribou**
Adds `sign-git-commit` config referenced in #12696

### CODE REVIEW

**Comment by tribou** [comment]
...looks like I'll have to keep `commitFlag` from being passed to `git.chainableExec()` if `git-sign-commit=false`

**Review by zkat — APPROVED** [review]
This LGTM! It seems reasonable enough to include, so we'll have it as part of the next release. Thanks!

**Comment by tribou** [comment]
@zkat Just a heads up! I originally wrote this PR against `npm@^3` and haven't tested it at all in v5 😟 

I'm afraid it might need to be rewritten 😢

**Comment by zkat** [comment]
@tribou I think you'll find the conflict to be very small! It would be great if you just resolved the conflict and pushed out a new, rebased version -- or I can do it myself when it's time to merge (although that'd be more work for me lolsob). Your patch is straightforward enough :)

**Comment by tribou** [comment]
Ah, I didn't realize that! I'll try to look into it soon

**Comment by zkat** [comment]
I'm doing my merges today, and it looks like this isn't ready yet, so I'm pushing it out until next time we do a PR sweep.

**Pull request merged**
