### PR TITLE
Do not needlessly require bash

### PR DESCRIPTION
**Pull request by AMDmi3**
This script does not need any bash features and works fine with any POSIX-compliant shell. Fix for systems which do not have /bin/bash (e.g. FreeBSD).

### CODE REVIEW

**Comment by KenanY** [comment]
@AMDmi3 Why not send this [upstream](https://github.com/npm/node-which)?

**Comment by AMDmi3** [comment]
I wasn't aware that's separate project. [Done](https://github.com/npm/node-which/pull/38).

**Comment by legodude17** [comment]
I believe this can be closed, right?

**Comment by zkat** [comment]
closing. the new version of `which` will be included once released as part of our usual dep update process. Thanks for paying attention to this!

**Pull request closed without merging**
