### PR TITLE
error-handler: put npm-debug.log in cache folder

### PR DESCRIPTION
**Pull request by kenany**
This is, like, the fourth PR to implement this.

I see more and more users now attaching their `npm-debug.log`s to issues as `.docx`, `.pdf`, and `.zip`. Frankly I don't want to have to download any of these just to see someone's error log. I would like to see more users upload their logs to `gist.github.com` instead. `npm report` will help a lot with this, so I would like to get this prerequisite landed.

### CODE REVIEW

**Comment by iarna** [comment]
@KenanY My main concern here is that it not fill up user's hard disks. This is particularly a concern for CI environments that could have hundreds of failing runs a day.

To land this, I'd like to see some mechanism that limits the number of logs kept in that directory to something reasonable (say, 10). This could be achieved by, if 10 or more logs exist at startup, removing the oldest until only 9 remain. Doing this at startup means that we don't have to worry about trying to do a bunch of things in the midst of an exit handler.

**Comment by KenanY** [comment]
@iarna Can't believe I somehow missed your comment after all this time :(

I'll look into implementing https://github.com/npm/npm/issues/7614 within this PR as well then.

**Comment by legodude17** [comment]
Something kidof related that would also help a `npm report` is to write to a `npm-debug.json` that includes parsable output so `npm report` already knows the error.

**Comment by KenanY** [comment]
Added `logs-max` config (name is akin to `cache-max`). Log deletion needs to happen after config is loaded so I simply implemented that within `npm.load()` itself. Might be a better place for it elsewhere; open to suggestions.

Just needs a test now.

**Comment by iarna** [comment]
Yeah, this seems otherwise ready. I'm going to see if I can't get tests written for it.

(Note from work in progress: I did end up tweaking the filename to be a bit more human readable.)

**Comment by iarna** [comment]
I fixed a bug (the reported log file name was incorrect) and added a test, so this'll land this week!

**Comment by iarna** [comment]
And it's merged into `release-next` as 04fca22

**Pull request closed without merging**
