### PR TITLE
WIP: linter-enforced coding style

### PR DESCRIPTION
**Pull request by othiym23**
@iarna, @isaacs and I have broadly agreed on an approach for coming up with  coding style guidelines for npm:
- All rules will be enforced by linter.
- npm will be remaining a semicolon-free zone.
- @isaacs would prefer to see dependencies that are hosted under the npm GitHub organization be allowed to keep their existing style, but @othiym23 would prefer to see a certain degree of uniformity across the code base. Either way, linting work will be restricted to `npm` until we have the core repo's style guidelines in a state we're all comfortable with.
- Changes to the coding style will come in as pull requests against the linting rulesets and `doc/misc/coding-style.md`. The two must be kept in sync.
- [ ] Linting will happen as part of `npm pretest`.
- [ ] Any changes or more restrictive lint rules will be applied all at once. Having failing lint checks on master is not cool.

The goal is to make the npm code base more welcoming to contributors who want to jump in to fix an issue or two, file them as PRs, and get out. I believe that a good way to reach that goal is to use linting to enforce consistency across the code base, as well as a certain degree of conventionality. It will be a lot easier for contributors to know if their changes are correct.

So far there are rules for `eslint` and `jscs`. I will probably include an `.editorconfig` in this PR eventually as well. Having multiple sets of rules is cumbersome, but I haven't yet figured out if I can do what I need with just one of `eslint` or `jscs` without spending a bunch of time writing custom rules.

So far there is only one major deviation from the current coding style guidelines, which is clearing out comma-first style. I have no strong preference (having gone both ways for various Node projects), and @isaacs is still a fan, but Node community practice has been moving away from it for a while.

The updated files on this PR are mostly just examples to see how many changes result from the current style guidelines; @iarna has been working for months on a new version of npm that makes substantial changes to the installer code, and I'll probably rebase this PR against that branch as soon as is practicable.

Comments are welcome, as is thoughtful bikeshedding, but please remember that the goal here is to make it easier for newcomers to contribute, not to enforce orthodoxy or grind your particular ax.

### CODE REVIEW

**Comment by rlidwka** [comment]
> So far there is only one major deviation from the current coding style guidelines, which is clearing out comma-first style.

There are two issues here that need to be discussed separately. Comma in variable declarations and comma placement in objects. I saw a lot of people moving to one-var-per-variable style to make git diffs easier, but I don't believe community opinion is changed with respect to comma-first object style.

> I believe that a good way to reach that goal is to use linting to enforce consistency across the code base

While unified style might make easier to read the code, I think enforcing it for every PR will only make life harder for new contributors.

The issue is that Travis CI can't distinguish between style errors and actual errors. And many projects have an implicit or explicit rule of "if build fails, we won't merge it". So it creates a red tape barrier to new contributors (who don't know the code style), forces them to open logs, spend time figuring out why it fails only to find out that the whitespace is misplaced.

There is an alternative to this. Since npm doesn't use "the green button" anyway, a project's maintainer (or whoever is merging PR) could fix style errors as he likes when merging from git CLI. Thus, it avoids putting this hassle onto individual contributors. As far as I can see, this practice works well for expressjs/jshttp/pillarjs projects.

**Comment by othiym23** [comment]
>  I saw a lot of people moving to one-var-per-variable style to make git diffs easier

That's not why I've made that change -- there have been several instances since I started working on npm full-time where careless or inconsistent use of commas in declarations have led to variables leaking into global scope, and at least twice when that has caused errors.

**Comment by smikes** [comment]
> variables leaking into global scope, and at least twice when that has caused errors.

+1 to one-var-per-line for this reason alone.  If you catch me doing it any other way, please call it out.

**Comment by yoshuawuyts** [comment]
Maybe this is interesting: https://github.com/feross/standard. From what I've seen it appears quite some prolific npm authors are taking it up. (:

**Comment by terinjokes** [comment]
@yoshuawuyts and I've seen other prolific npm authors take up `jsfmt`.

**Comment by yoshuawuyts** [comment]
@terinjokes yeah, there's a bunch of tools out there. `standard` disallows semicolons though, and cuts having to maintain a bunch of config files in the repo root.

**Comment by othiym23** [comment]
@feross as much as said he did it for the lols, and while there are points of congruency between the `standard` code style and npm's, one of the goals for this task is to make the code base more consistent while, as much as is practicable, codifying the pre-existing style. Among other things, I have to do a fair amount of `git blame` and `git log -S` on the npm code base, and so I don't want to do anything that's going to complicate that process more than necessary.

And there are plenty of uh idiosyncratic aspects of the code base's style, so it's a thin line to walk.

**Comment by feross** [comment]
I wrote `standard` (JavaScript Standard Style) to enforce consistency in my modules and save code review time. Like @dougwilson, I prefer to fix style issues myself instead of putting that work on contributors. It creates a lot of work for me, but it's better than the alternative: discouraging future contribution, adding days of back-and-forth to PRs, and increasing the probability that the PR is abandoned.

@maxogden, @mafintosh, and I (and others?) have started using it in our modules. Max wrote a simple auto formatter, [standard-format](https://github.com/maxogden/standard-format), to fix some of the easier cases. There's also an [automatic lint plugin](https://github.com/Flet/Sublimelinter-contrib-standard) for Sublime Text – it works great!

There's interest in an automatic code formatter, so I'll probably add something based on `jsfmt` so you'll be able to run `standard format` and it will fix most everything.

It's really difficult to add a bunch of new strict rules to an existing codebase (case in point: this PR already needs to be rebased), so @othiym23's approach of manually curing the lint rules (and ramping up strictness as the codebase improves) makes a lot of sense to me :+1: 

That said, the [npm coding style](https://github.com/npm/npm/blob/master/doc/misc/npm-coding-style.md) (with the new comma-last rule change) is basically identical to JavaScript Standard Style! Out of curiosity, I ran `standard` on npm, with this PR applied. `standard` is enforcing these additional rules on the codebase:

- No unused variables
- Strings should always use single quotes (exception: double quotes are okay to avoid escaping).
- Consistent spacing (one space after `,` in argument lists, one space before/after infix operators like `+`, etc.)
- Object literals require space before value (good: `{ key: value }`, bad: `{ key:value }`)
- Multiple consecutive blank lines not allowed
- Spaces after `//` in comment (good: `// my comment`, bad: `//my comment`)
- No octals

If you guys have interest in adopting `standard`, I'll happily add you as owners/collaborators. We can also add the npm codebase to the [test suite](https://github.com/feross/standard/blob/master/test.js#L3-L9) so we're careful that eslint/jscs version bumps / rule changes don't cause previously passing code to suddenly start failing.

**Comment by othiym23** [comment]
Closing in favor of #7442, which just goes ahead and pulls the ripcord on making npm follow `standard`. @feross, you should go look at what you hath wrought – if your browser doesn't explode trying to display it. It's pretty :lollipop: (for lolololololollipop).

**Comment by marr** [comment]
Where did .editorconfig go? It should be possible to use its support if I `make link` and set it to say, 4 so I could have normal behavior in my editor when tweaking package.json files.

**Comment by othiym23** [comment]
@marr I'm still planning on adding an `.editorconfig` to the npm source tree once the `npm@3` codebase stabilizes enough for me to get that codebase passing `standard`'s quality checks, but that will only affect npm itself. Is that what you were asking for, or did you have something more sweeping in mind?

**Pull request closed without merging**
