### PR TITLE
scoped bundledDeps fixes

### LINKED ISSUE #8614: npm pack doesn't bundle scoped bundledDependencies
test package.json
```json 
{
  "name": "npm-bundle-test",
  "version": "1.0.0",
  "dependencies": {
    "@myscope/debug": "*"
  },
  "bundledDependencies": [
    "@myscope/debug"
  ]
}
```

`npm install` creates `node_modules/@myscope/debug/`, but `npm pack` ignore all scoped bundled dependencies 

```sh
# tar -tvf npm-bundle-test-1.0.0.tgz`
-rw-r--r-- 501/20          152 2015-06-19 16:09 package/package.json
```

It probably does not work because scoped modules are in @*scope* subdirectory.

### PR DESCRIPTION
**Pull request by zkat**
@forivall kindly set up a pr over at https://github.com/npm/fstream-npm/pull/22 to fix #8614. This branch adds a basic bundledDeps test to verify the changes, and will eventually include the dep upgrade commit.

### CODE REVIEW

**Comment by forivall** [comment]
Hmm, it looks like there was bundledDependency checking being done in tar as well: Once I removed it, it works!

I just did a quick visual inspection, so I don't know if anything was different between tar.js's `BundledPacker.prototype.applyIgnores` and fstream-npm's `Packer.prototype.applyIgnores`.

https://github.com/forivall/npm/commit/27fdf27674aaecd3a5923b94f3706cafffc0f882

**Comment by zkat** [comment]
Hey @forivall -- I know this looks terrible (and it is), but... that's actually kinda how it has to be. And it keeps biting us when we forget. That whole stack is getting rewritten eventually, so the only thing you can really do is duplicate whatever code you need to dupe across both implementations :( Otherwise, things start going awry. It's basically needed for transitive dependencies (see #13088 and #13089)

**Comment by forivall** [comment]
ah, yeah, i diffed it

https://gist.github.com/forivall/58d56561293b6740241343063d8657cc

Well, that explains why transitive dependencies weren't being included when I was using fstream-npm directly for a bundler, and I had to resort to this hack: https://gist.github.com/forivall/80b4284065a354f72f1766504dc7aa5d

So, I guess my change in fstream-npm needs to be duplicated in tar.js's `BundledPacker.prototype.applyIgnores` 😿

**Comment by forivall** [comment]
https://github.com/npm/npm/compare/npm:zkat/scoped-bundled-fix...forivall:forivall/scoped-bundled-fix

**Comment by iarna** [comment]
Essentially `fstream-npm` holds the npm@2 logic, and `lib/utils/tar.js` holds the npm@3 logic.

Yeah, this sucks– it was necessitated by the npm@3 bundle dependency logic needing access to npm@3 internals and `fstream`'s extension mechanism not allowing finer grained insertion of them.

That last patch looks good to me.

**Comment by zkat** [comment]
This is in our next release branch and will be included in the next release :)

**Pull request merged**
