### PR TITLE
shrinkwrap: Improve detection of pkgs req'd by top level dev deps

### PR DESCRIPTION
**Pull request by iarna**
Specifically, we now don't blow the stack on dev deps that have cycles.

Fixes: #13327

### CODE REVIEW

**Comment by othiym23** [comment]
How do you feel about the idea of some unit tests demonstrating the expected range of inputs for `isDevDep` and `isProdDep`?

**Comment by othiym23** [comment]
The changes look good (if only because they simplify things a bit), but I'm wondering if there's a way we can fence in the behavior here a little more tightly with tests and make this code generally more resistant to regressions and bugs in the future.

**Comment by iarna** [comment]
`is(Dev|Prod)Dep` are pretty minimal functions. Surely I can write tests for them, but I'm a little dubious that it's the best use of our time. They're pretty uninteresting. (My experience is telling me: That's not where we'll have bugs. I would be very surprised if we ever saw a bug in either of those functions.) I guess what I'm saying is: If you feel that's necessary I'll do it, but if I were making the decision I'd move on to other, IMHO more valuable, work.

Putting aside the refactoring, there are only two substantive changes here:

https://github.com/npm/npm/pull/13399/files#diff-14efa09b371358c4c6934dc02a7884efR158

Whence I added `seen` to break cycles.

And 

https://github.com/npm/npm/pull/13399/files#diff-97a53acbc070b7edcd97498046a5eee3R53

Where I simplified the test as we don't need to identify transitive dev deps, just direct ones.

If your goal is just to have more testing around this corner I'd prioritize unit testing of `isOnlyDev` well ahead of them. It's not exported, but it is a moderately complex recursive function, of sufficient obtuseness that I wrote substantial comments for it.

**Comment by iarna** [comment]
This is merged and will be in the next release (scheduled for later today).

**Pull request closed without merging**
