### PR TITLE
add script for updating AUTHORS file

### PR DESCRIPTION
**Pull request by kenany**
Since a patch seems to be welcome for https://github.com/npm/npm/issues/4829, I decided to take a stab at it.

`.mailmap` file removes duplicates for contributors with multiple emails. There are perhaps more lines to be added to this file but for the time being I'm submitting this for review to see if it is even desired anymore :)

### CODE REVIEW

**Comment by othiym23** [comment]
The current information is super out of date, because this is a task I didn't pick up when I started maintaining and releasing npm. So this is great! Could you add a `Makefile` stanza to run the script and check in the changes, and have `make publish` depend on that stanza? Thanks!

**Comment by KenanY** [comment]
@othiym23 Awesome! I've updated the PR to include the `Makefile` changes. My `make`-fu is no good but the stanza seems to work on my machine :)

**Comment by othiym23** [comment]
I'll try to get this merged on the next release day (when I'm running on a system that has a solid `make` implementation available).

**Comment by othiym23** [comment]
Landed in 102708704c8c4f0ea99775d38f8d1efecf584940. Thanks!

The next thing to do with this would be to ensure that the AUTHORS file has a stable sort order, so we don't see a huge amount of diff churn between runs.

**Comment by KenanY** [comment]
@othiym23 

> stable sort order

Erm, I'm not sure what happened in https://github.com/npm/npm/commit/f4c3172b4bab1f264dfac85968f2bee33d579a67 but the script should be sorting by first contribution (hence the `git log --reverse`). At least, it does on my machine; sanity test is that Isaac should appear first :)

**Comment by othiym23** [comment]
>  I'm not sure what happened in f4c3172

I merged your change and ran `make authors`. ;) git 2.something, OS X 10.10, git installed via homebrew.

**Comment by KenanY** [comment]
@othiym23 But when I run `make authors` on `HEAD` right now I get Isaac on top :scream: git 2.2.2 and Linux 3.17.6.

``` bash
$ make authors
[master 5ec2da1] update AUTHORS
 1 file changed, 156 insertions(+), 153 deletions(-)

$ git show 5ec2da1
```

``` patch
commit 5ec2da1ae1ad7aee34aa1e16543694d36be8850b
Author: Kenan Yildirim <kenan@kenany.me>
Date:   Mon Jan 26 19:21:15 2015 -0500

    update AUTHORS

diff --git a/AUTHORS b/AUTHORS
index 2de391d..1fd69a6 100644
--- a/AUTHORS
+++ b/AUTHORS
@@ -1,4 +1,25 @@
 # Authors sorted by whether or not they're me
+Isaac Z. Schlueter <i@izs.me>
+Steve Steiner <ssteinerX@gmail.com>
+Mikeal Rogers <mikeal.rogers@gmail.com>
+Aaron Blohowiak <aaron.blohowiak@gmail.com>
+Martyn Smith <martyn@dollyfish.net.nz>
+Charlie Robbins <charlie.robbins@gmail.com>
+Francisco Treacy <francisco.treacy@gmail.com>
+Cliffano Subagio <cliffano@gmail.com>
+Christian Eager <christian.eager@nokia.com>
+Dav Glass <davglass@gmail.com>
+Alex K. Wolfe <alexkwolfe@gmail.com>
+James Sanders <jimmyjazz14@gmail.com>
+Reid Burke <me@reidburke.com>
+Arlo Breault <arlolra@gmail.com>
+Timo Derstappen <teemow@gmail.com>
+Bart Teeuwisse <bart.teeuwisse@thecodemill.biz>
+Ben Noordhuis <info@bnoordhuis.nl>
+Tor Valamo <tor.valamo@gmail.com>
+Whyme.Lyu <5longluna@gmail.com>
+Olivier Melcher <olivier.melcher@gmail.com>
+Tomaž Muraus <kami@k5-storitve.net>
 Evan Meagher <evan.meagher@gmail.com>
 Orlando Vazquez <ovazquez@gmail.com>
 Kai Chen <kaichenxyz@gmail.com>
@@ -7,232 +28,214 @@ Geoff Flarity <geoff.flarity@gmail.com>
 Max Goodman <c@chromakode.com>
 Pete Kruckenberg <pete@kruckenberg.com>
 Laurie Harper <laurie@holoweb.net>
-Neil Gentleman <ngentleman@gmail.com>
-Kris Kowal <kris.kowal@cixar.com>
```

Maybe some difference in our git configs?

**Comment by othiym23** [comment]
I will take a look at my git config, but it's pretty standard. Could this be some weird locale thing?

**Comment by KenanY** [comment]
> weird locale thing

Hopefully not :/

``` bash
$ locale
LANG=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

I mean, one of two things is doing something wrong: the `git log` or `awk`...

**Comment by KenanY** [comment]
@othiym23 sounds like @rvagg is seeing the same issue on OSX at io.js: https://github.com/iojs/io.js/pull/713

**Comment by aetsher** [comment]
aetsher

**Comment by aetsher** [comment]
aetsher

**Pull request closed without merging**
