### PR TITLE
fixed link package name

### PR DESCRIPTION
**Pull request by yadimon**

### CODE REVIEW

**Comment by KenanY** [comment]
I believe `"redis"` is correct, see https://github.com/npm/npm/pull/7538.

**Comment by yadimon** [comment]
then other `node-redis` names should be renamed to `redis`?

**Comment by KenanY** [comment]
Sure, it would probably be less confusing that way. We could even use a different module entirely.

**Comment by iarna** [comment]
As @KenanY points out, `redis` is the name of the module, so I'm going to close this. But I would be interested in a PR that makes the docs more consistent in this respect (even using a different module).

**Pull request closed without merging**
