### PR TITLE
Fix for #7120

### PR DESCRIPTION
**Pull request by silkentrance**
Please review. Needs additional work:
- additional warnings
- maybe some refactoring to get rid of newly introduced duplicate code
- one chownr has not been dealt with yet
- additional test cases?
- update documentation on npm --force install

### CODE REVIEW

**Comment by silkentrance** [comment]
The build fails but I cannot see any PR related issues there, knock on wood.

**Comment by othiym23** [comment]
It's tough to review this without tests and with TODOs scattered through the diff. This still feels like overkill to me, though -- you are still the only person who's run into this problem in the wild, and this is a fair amount of new conditional logic to deal with what feels like an edge case's edge case. However, if you want a complete review of this, fill out the rest of the patch and I'll go over it.

**Comment by silkentrance** [comment]
I'd been busy, so sorry for not attending to this. Will try to have a look at this in the upcoming week.

**Comment by silkentrance** [comment]
With npm/fstream@1679e2a905692c4659b45b1ec74d67a41214cba5 in place some of the issues might have gone away already.

**Comment by silkentrance** [comment]
Good news, the patch for fstream seems to have done the trick. Closing this one now.

**Pull request closed without merging**
