### PR TITLE
cache: ignore enoent on chownr while adding packages to cache

### LINKED ISSUE #12669: Race condition while adding local packages to cache
We are experiencing a weird problem while installing local (`file:`) packages with npm. It happens more frequently with `npm@3` and local scoped packages, but it's totally random.

```
⬢ npm run clean && npm cache clean && npm i

> npm-bug@1.0.0 clean /Users/julianduque/Sandbox/npm-bug
> rm -rf node_modules ns-*/node_modules

npm ERR! addLocal Could not install /Users/julianduque/Sandbox/npm-bug/ns-router
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/julianduque/.nvm/versions/node/v4.4.3/bin/node" "/Users/julianduque/.nvm/versions/node/v4.4.3/bin/npm" "i"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.9
npm ERR! path /Users/julianduque/.npm/@ns/root/1.0.0/package.tgz.783164638
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall lstat

npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/julianduque/.npm/@ns/root/1.0.0/package.tgz.783164638'
npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/julianduque/.npm/@ns/root/1.0.0/package.tgz.783164638'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/julianduque/Sandbox/npm-bug/npm-debug.log
```

Debugging this issue it happens in the following function call:

https://github.com/npm/npm/blob/master/lib/cache/add-local.js#L110

So, while `fs-write-stream-atomic` is still creating / cleaning up the temporary package file, `chownr` reads the temporary file on this function call: https://github.com/isaacs/chownr/blob/master/chownr.js#L8 but when is doing the `lstat` here: https://github.com/isaacs/chownr/blob/master/chownr.js#L18 the file doesn't exist and it crashes.

Adding some output to `fs-write-stream-atomic` and `chownr` to track down the error:
```
* npm:thenPack  /Users/julianduque/.npm/@ns/router/1.0.0/package.tgz
* npm:thenPack  /Users/julianduque/.npm/@ns/root/1.0.0/package.tgz
- fs-write-stream-atomic: /Users/julianduque/.npm/@ns/router/1.0.0/package.tgz.2454299972
- fs-write-stream-atomic:  /Users/julianduque/.npm/@ns/root/1.0.0/package.tgz.2894581287
~ npm:moveIntoPlace  /Users/julianduque/.npm/@ns/router/1.0.0/package.tgz.2454299972 1462994637760
~~ chownr childrens:  1462994637761 /Users/julianduque/.npm/@ns
[ 'root', 'router' ]
~~ chownr childrens:  1462994637762 /Users/julianduque/.npm/@ns/root
[ '1.0.0' ]
~~ chownr childrens:  1462994637762 /Users/julianduque/.npm/@ns/router
[ '1.0.0' ]
~ fs-write-stream-atomic:moveIntoPlace  /Users/julianduque/.npm/@ns/root/1.0.0/package.tgz.2894581287 1462994637762
~~ chownr childrens:  1462994637762 /Users/julianduque/.npm/@ns/root/1.0.0
[ 'package', 'package.tgz.2894581287' ] // ---> booom, temporary file
~~ chownr childrens:  1462994637762 /Users/julianduque/.npm/@ns/router/1.0.0
[ 'package', 'package.tgz' ] // ---> this looks good though
npm ERR! addLocal Could not install /Users/julianduque/Sandbox/npm-bug/ns-router
....
npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/julianduque/.npm/@ns/root/1.0.0/package.tgz.2894581287'
```

It seems like a race condition in `fs-write-stream-atomic` or in the add-local logic, but I'm not sure how to fix it to submit a PR.

I have a small project to reproduce this issue, let me know if you need it for debugging purposes.

@othiym23 - copying you since you give us the clue about `fs-write-stream-atomic`.

#### Possibly Related

* https://github.com/npm/npm/issues/10656

### PR DESCRIPTION
**Pull request by julianduque**
Fixes #12669 (See ticket for more information about the issue)

### CODE REVIEW

**Comment by zkat** [comment]
@julianduque thanks for this! We spent a little while longer talking about alternative solutions, possible effects of this, and ended up agreeing that this is the best way to go about it.

Since this part of the code is *particularly tricky* to test, I'll probably write the tests for this myself (as I just wrote tests for a https://github.com/npm/npm/pull/13023, which is for different race conditions in the same region of code.

Heads-up that will probably involve me putting up a new PR with your patch in it once that's done, assuming I can pull off replicating it with mocks.

**Comment by zkat** [comment]
Alright, I've pulled in your patch into a larger PR over at #13023 (and credited you accordingly) and I'm closing this one. Please track that one for future changes, and thank you so much for your help! :)

**Comment by julianduque** [comment]
@zkat this is great news!! Thank you very much for landing it <3

**Comment by zkat** [comment]
just dropping a note in here that the changes related to this have been merged into both `master` and `lts` branches. Cheers again :)

**Pull request closed without merging**
