### PR TITLE
Update npm.md

### PR DESCRIPTION
**Pull request by andresilveirah**
small grammar fix

### CODE REVIEW

**Comment by zkat** [comment]
LGTM. Thanks for the patch :)

**Comment by andresilveira** [comment]
Such a small fix that I'm not sure I can call it contribution 😄

**Comment by zkat** [comment]
This was included in `npm@3.9.4`. Thanks! 🎉 

And really, small contributions are fine. It's nice to see community people drop by and participate. :)

I'm leaving the PR open until this gets integrated into LTS, btw. That'll be... in the future.

**Comment by zkat** [comment]
I've merged this into the LTS branch, and it'll go out whenever that one gets released again. Thanks again!

**Pull request closed without merging**
