### PR TITLE
Fix `npm version` not working in cygwin

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
ok this has to be done differently, but has to detect cygwin

**Comment by ForsakenHarmony** [comment]
Where does `localPrefix` come from?

**Comment by iarna** [comment]
@ForsakenHarmony `localPrefix` is the current module directory.. so if I'm in `/home/me/my-project/a/b/c` and there's a `package.json` in `/home/me/my-project/my-project` then that's what `localPrefix` will be set to. It's the top level of the current project and where `node_modules` will be created. It contrasts with `globalPrefix` which is where things go when you use `npm i -g`.

It's set in `lib/config/load-prefix.js` and the value is computed by [`find-npm-prefix`](https://www.npmjs.com/package/find-npm-prefix).

If you've got more questions or would like to talk about this and get responses in a somewhat more timely fashion, I encourage you to drop by #js-npm on the https://package.community Discord!

**Comment by zkat** [comment]
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

**Pull request closed without merging**
