### PR TITLE
run-script: prefer current node in run-script (Fixes: #11175)

### PR DESCRIPTION
**Pull request by segrey**

### CODE REVIEW

**Comment by iarna** [comment]
See also: https://github.com/npm/npm/issues/11175

**Comment by iarna** [comment]
Looks good– scheduling this for next week.

**Comment by othiym23** [comment]
This will fix #9253 once it ships.

**Comment by iarna** [comment]
This was merged into 3.7.0! =)

**Comment by segrey** [comment]
Thanks!

**Comment by pesho** [comment]
@othiym23 @iarna @segrey I believe this patch is harmful and should be reverted.

For example in my case, I run a npm script inside a Python [virtualenv](https://pypi.python.org/pypi/virtualenv). Inside the `virtualenv` a custom PATH is set, which points to a different Python interpreter. However, after upgrading to npm 3.7.x, npm started prepending `/usr/bin` to the PATH in lifecycle scripts because of this PR, which caused bad breakage.

It shouldn't be npm's call to prepend `/usr/bin` to the PATH, users may have valid reasons to put something else first. The issue which prompted this (#9253) should be fixed by the user himself, by setting PATH correctly.

**Comment by othiym23** [comment]
Hmm. In effect, this is due to two `virtualenv`-like tools colliding. Both `virtualenv` and npm want to control `PATH` (& many other things, most of which fortunately don't collide) in the child environments they control (and Node version managers like `nvm` and `nave` complicate this even more, as #11175 demonstrates). The question for me is whether we can make both work at the same time without too much conflict or custom configuration.

I think this patch better satisfies most users' expectations that the Node that was used to run npm will be used to run package scripts invoked within the context of that npm operation. I'm reluctant to revert this change without first taking a hard look at the problem space as a result. 

Because package scripts are invoked via shebang lines or command shims that read the path, npm has to do this indirectly by manipulating the `PATH` passed to child processes. Reverting this patch forces people into really nonergonomic corners for some common use cases, so my questions for you are how does this break things for you? What have you tried already to work around this? Are there other tools, like setting `PYTHON` in the virtual env, that will around this?

**Comment by pesho** [comment]
> Both virtualenv and npm want to control PATH

There should be some sane limits to that. There is a difference between `npm/bin/node-gyp-bin` and `node_modules/.bin` on one side, and `/usr/bin` on the other side. The first two are either closely-related to, or controled directly by `npm`. It makes sense to put them in the front of `PATH`. The third one is just too general, `npm` has no idea what dangerous viruses it might contain (:smile:). 

> so my questions for you are how does this break things for you? What have you tried already to work around this? Are there other tools, like setting PYTHON in the virtual env, that will around this?

For now, I worked around this by entering the `virtualenv` from inside the run-script, like this:

```json
  "scripts": {
    "local": "env `cat .env` bash -c 'source venv/bin/activate && exec python2 main.py'"
  }
```

I don't think this should be necessary. It's better to document that run-scripts will respect the contents of `PATH` and execute the `npm` it points to, and the user should have it set correctly if having multiple `npm` versions installed.

**Comment by pesho** [comment]
Alternative idea: Put symlinks to the expected `node` and `npm` versions inside `node_modules/.bin`. That way the expected ones will always be executed by run-scripts, without dangerously messing with `PATH`.

**Comment by segrey** [comment]
Agree that changing `PATH` can be dangerous. The idea to put symlinks inside `node_modules/.bin` looks reasonable, but it has minor problems:
* two npm scripts may be running concurrently using different node interpreters
* some package may contribute `node_modules/.bin/node` or `node_modules/.bin/npm`.

How about another fix: keep `PATH` unchanged if `which node` on current `PATH` returns `process.execPath`? It doesn't solve the issue completely, but it reduces the probability of colliding.

**Comment by pesho** [comment]
> The idea to put symlinks inside node_modules/.bin looks reasonable, but it has minor problems:

Indeed. Here is a small modification which sidesteps these problems: 

* Create a temporary directory on each `run-script` invocation, e.g. `/tmp/npm/run/<random_id>`, and put the symlinks there. Then prepend that temporary directory in front of `PATH`.
* The symlink to `npm` could even be safely put in `npm/bin/node-gyp-bin` as part of the package, as this directory already gets prepended to `PATH`. This alone wouldn't be enough though, as we also want a symlink to `node`.

The `/tmp` variant would probably leave Windows users behind, but I don't think it's too common to have multiple `npm`/`node` installations in Windows.

> How about another fix: keep PATH unchanged if which node on current PATH returns process.execPath? It doesn't solve the issue completely, but it reduces the probability of colliding.

Not ideal, but definitely an improvement. At least in my case it would solve the issue I encountered.

**Comment by segrey** [comment]
Yep, that's a safer approach (a bit complicated, but seems it can't be simplified).
The question I have is should we care about globally installed modules and make them available in `/tmp/npm/run/<random_id>` too?

It's possible to use `require('os').tmpdir()`. On Windows it will probably return `C:\Users\<username>\AppData\Local\Temp`, but I didn't test.

**Comment by pesho** [comment]
> The question I have is should we care about globally installed modules and make them available in /tmp/npm/run/<random_id> too?

I think not. If a `run-script` relies on a given module, it should be installed locally. It shouldn't rely on global modules.

> It's possible to use require('os').tmpdir(). On Windows it will probably return C:\Users\<username>\AppData\Local\Temp, but I didn't test.

Nice :) Although on Windows we'd probably have bigger problems - I think administrator privileges are required in order to create a symlink there.

**Comment by narqo** [comment]
@othiym23 @iarna is it possible to have this fixes in `npm@2x`? There is the `2.14.17` milestone here, but looks like this fixes still haven't been ported to `2.x`.

**Comment by iarna** [comment]
milestones relate to which release day it was merged. labels tell the story of what it was merged into.

**Comment by segrey** [comment]
@pesho JFYI there is an attempt to mitigate possible harm caused by this change https://github.com/npm/npm/pull/12968

**Pull request closed without merging**
