### PR TITLE
help: Implement new help message like did-you-mean

### PR DESCRIPTION
**Pull request by watilde**
I just tried to implement https://github.com/npm/npm/issues/4324. Add new message to display suggestions when users run undefined commands and it makes users notice thier typo. I guess this feature makes npm more user-friendly.

I supported the following three cases:
- there is no suggestion
- there is a one suggestion
- there are some suggestions

e.g.

there is no suggestion, displays the help message as usual:

```
$ npm wombat

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/watilde/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.7 /Users/watilde/Development/npm
```

there is a one suggestion, displays the help message along with the suggestion:

```
$ npm food

npm: 'food' is not an npm command. See 'npm help'.

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/watilde/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.7 /Users/watilde/Development/npm

Did you mean this?
    root
```

there are some suggestions, displays the help message along with the suggestions(max 3):

```
$ npm jet

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/watilde/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.7 /Users/watilde/Development/npm

Did you mean one of these?
    set
    get
```

### CODE REVIEW

**Comment by msikma** [comment]
I would suggest maybe changing "is not a npm command" to "is not an npm command" since it sounds a bit nicer. But :+1: for this idea, would be very good to have this!

**Comment by watilde** [comment]
@msikma Thanks for your comment! I updated the description of this pull request and my implementation :)

**Comment by othiym23** [comment]
This is neat, but it's at odds with the existence of `npm isntall` and `npm verison` and the other built-in affordances npm has for clumsy fingers. It should be one or the other, in my opinion, because otherwise people are going to have a hard time understanding why npm sometimes just accepts a typo and does something, and sometimes it prints out a "did you mean x?" message. It should be one or the other (and we should _definitely not_ add the ability to autocorrect typos, because I've literally lost count of the number of times that caused something _very bad_ to happen to me with git, until I permanently disabled it).

I like the current strategy (and also think it's part of npm's quirky charm), but in some ways, this patch is a more general solution (which for a lot of people probably wins out over quirkiness). What do you think, @watilde?

**Comment by msikma** [comment]
Personally I like the approach in this PR because to me it seems like a bit better idea to soft redirect someone to the correct command, rather than accepting `isntall` as though `install` was typed. It would be nice to have one consistent and forwards-compatible system for this. Maybe the existing ones can be kept? Then again, having full consistency is probably worth it.

**Comment by watilde** [comment]
@othiym23 I don't think only adding an affordance is the only best way for all clumsy fingers because you know the typo usually has totally different bias is depending on people's background(, for example: many Japanese people often make mistake when they use "r" or "l"). However I like current built-in typo aliases, it actually works well. To have both solution, how do you think about it separates aliases, normal cmdList, plumbing as a module like lib/cmd/aliases.js and displays suggestion only for normal cmdList? It is probably worth it like @msikma said.

**Comment by watilde** [comment]
I just pushed updates related my proposal like I said to separate inside command list. Eventually this did-you-mean implementation is only for basic commands, not for aliases and plumbing commands. Also, now we can list commands for suggestions in `config/cmd.js` flexibly. Could I have your suggestion on this please?

**Comment by watilde** [comment]
Finally we have [a shorthand list](https://github.com/npm/npm/blob/master/lib/config/cmd-list.js) which is aliases except affordances in https://github.com/npm/npm/pull/11761 and then eventually we can display did-you-mean suggestions for all commands except affordances. That is the detail of the commit I just rebased and updated :)

**Comment by watilde** [comment]
Well, how do you think that display suggestion list in the tail of help message?

```
$ npm jet

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/watilde/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.8.9 /Users/watilde/Development/npm

Did you mean one of these?
        set
        get
```

**Comment by langpavel** [comment]
@othiym23 :pray: :shipit: :relaxed:

**Comment by othiym23** [comment]
> how do you think that display suggestion list in the tail of help message?

I think it'll probably get lost in the bulk of the usage output, so some kind of shorter version that says they can run `npm --help` or `npm --long` along with the suggestions is best.

I'd also like to see `did-you-mean` at least pulled out into a separate module, and perhaps a separate package. For now, can you try pulling that out into a separate file within `lib/`?

Sorry to leave this one sleeping for so long – as always, we've been very busy, and I needed some time to get myself off the fence when it came to this request.

**Comment by watilde** [comment]
@othiym23 Ok! I've updated my patch referenced your comment, and did rebase master:

+ Separate the did-you-mean as a package
+ Create a wrapper of the package in util
+ Display the help message along with the suggestions(max 3)

**Comment by iarna** [comment]
Sorry about losing this in the shuffle, again. I've landed this as 6c03e5ab8 & 1ac470dd2 on `release-next`.

**Pull request closed without merging**
