### PR TITLE
Fix for #16083, add support for --silent flag with npm outdated.

### PR DESCRIPTION
**Pull request by wwalser**
Fix for #16083 which is a bug introduced in #14013.

This PR is a strict fix for what was said to be the intended behavior introduced in #14013. ```npm outdated --silent``` was suppose to maintain the old behavior of returning a success status code even if wanted or latest were out of date.

As an aside, this seems to me like the wrong implementation. It introduces a second meaning of the word "silent" and it may even clash with existing behavior, though I couldn't find an invocation where this was the case.

It seems to me that reusing silent is problematic. The real desire, I believe, is to be able to use ```npm outdated``` with some nuance. For example see facebook/fbjs/issues/213, where an out of date "wanted" may be a reasonable case for an error but "latest" may not be.

**Edit**: As @KenanY correctly points out, the collision of a command config option and loglevel shorthand causes problems. I suggest either dumping this feature and letting downstream consumers sort out the exit code for themselves _or_ creating a new option to ```npm outdated``` with name other than ```--silent```. I would prefer the later and I'm willing to change the PR to make that happen. Open to suggestions for what the config option should be called, ```---quiet```?

### CODE REVIEW

**Comment by watilde** [comment]
+1 on this. This is what I expected, but I missed it at the last PR. We need to update `test/tap/outdated-json.js` to fix the ci error.
> https://github.com/npm/npm/blob/latest/test/tap/outdated-json.js#L83

**Comment by KenanY** [comment]
As it stands, this breaks the `--silent => --loglevel silent` alias. Perhaps https://github.com/npm/npm/pull/16703/files#diff-3d20499d58f14c6f1edfe93d8ba8a8a2R115 should just check if `loglevel === 'silent'`?

**Comment by wwalser** [comment]
@KenanY I must be doing something wrong, I'm not able to make the ```--silent``` flag work with outdated on my system installed npm. 

screen shot 2017-05-24 at 10 38 04 am

**Comment by wwalser** [comment]
Ah, thanks for those details. I am probably missing something still as this doesn't actually break that feature. It just changes the return code to match what was described in #14013.

I mentioned my hesitation with the overlapping flag in my OP. Is that what you're describing?

Here I show a run with an ```.npmrc``` containing ```loglevel=http```.

example-with-silent

**Comment by KenanY** [comment]
Okay, so oddly enough, this doesn't break the feature I mentioned **for `npm outdated` specifically**. I'm not sure yet why there's a difference, but my example above _does_ demonstrate the issue I'm talking about (at least on my machine 😄).

**Comment by wwalser** [comment]
@KenanY You're right.

I haven't read enough of the code to tell why exactly. It makes sense that having something that is both a parameter and a shorthand causes a collision but why it functions properly for ```outdated``` is a mystery to me.

**Comment by iarna** [comment]
@wwalser This patch is breaking things because `--silent` is already an option, see the `shorthands` in `lib/config/defaults.js`.

**Comment by wwalser** [comment]
@iarna Yes, that's discussed in the comments here, in the bug, and in the original change that introduced the bug. My proposed solution is to rename the flag or drop this fix and accept the knock on regressions. I'm happy with any decision. The bug this caused for me has been fixed down stream by ignoring the exit code.

**Comment by zkat** [comment]
Hi! We're moving repos to https://github.com/npm/cli/pulls! See [our blog post about the migration to npm.community](https://blog.npmjs.org/post/175587538995/announcing-npmcommunity) for details. As such, we're closing all active PRs on this repo.

Could you please re-open this PR against `npm/cli` instead? We're still interested in this patch so we hope you will! We'll continue discussion over there once it's moved. 💚

**Pull request closed without merging**
