### PR TITLE
Fix npm-logout to remove scope config if specified

### PR DESCRIPTION
**Pull request by wyze**
Addresses #10529

### CODE REVIEW

**Comment by iarna** [comment]
Hi there, thanks for your hard work! To be clear, this will need a test for us to land it.

**Comment by wyze** [comment]
Sorry, I meant to do that the next day! I added test, squashed, and rebased. My test passed, but on my machine not all passed. Hopefully they do on Travis!

**Comment by iarna** [comment]
Thanks! LGTM!

**Comment by iarna** [comment]
This landed in 3.8.2!

**Pull request closed without merging**
