### PR TITLE
Allow `npm version` to be run from subdirectories

### LINKED ISSUE #9099: npm version while in a subdirectory of the project increments the version but fails to commit to git
```
ariastewart@LM-BOS-00872654:cases (master:8dbeb8c)
:; npm version patch
v3.0.1
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "version" "patch"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.3
npm ERR! code 128

npm ERR! Command failed: git add package.json
npm ERR! fatal: pathspec 'package.json' did not match any files
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ariastewart/Projects/json-ometajs/test/cases/npm-debug.log
ariastewart@LM-BOS-00872654:cases (master:8dbeb8c Δ )
```

### PR DESCRIPTION
**Pull request by ekmartin**
Fixes #9099 by using the local `package.json` path when running `git add`. Was this something like what you were thinking of @othiym23? If it was I can add a small description of the behavior to the docs, just wanted to check first.

### CODE REVIEW

**Comment by othiym23** [comment]
I haven't had time to review this thoroughly, but if you think a note in the docs would be helpful, by all means add it! We'll try to get this into next week's releases.

**Comment by ekmartin** [comment]
No problem! Not sure if an update to the docs is needed, but I'm not familiar with the differences of opinion you were mentioning [here](https://github.com/npm/npm/issues/9099#issuecomment-125991344). If there's other results that would make sense when you run version from a subdirectory I agree that it probably should be clarified.

**Comment by othiym23** [comment]
Landed for `npm@3` as 954fa67f1ca3739992abd244e217a0aaf8465660, and will do the same for `npm@2` shortly. This is a well-done patch! Thanks for taking the time to put it together, and for including a test!

**Comment by othiym23** [comment]
Cherry-picked for `npm@2` as 529fa1ff2c6432a773af99a1c5209c0865f7a19c. Thanks again!

**Pull request closed without merging**
