### PR TITLE
Fix uninstall leaving nested modules directories with .bin

### LINKED ISSUE #10887: `npm uninstall` fails to remove some directories from node_modules resulting in ENOENT errors
Steps to reproduce:

top-level package.json:
```
{
  "dependencies": {
    "pkg-that-just-requires-gulp": "^1.0.0",
    "gulp": "^3.9.0"
  }
}
```

`pkg-that-just-requires-gulp` is a test package that just requires `gulp` as its only dependency.

Install the dependency tree:

```
$ npm install
```

Now, let's uninstall `gulp`:

```
$ npm uninstall --save gulp
```

We now **expect** `npm ls` to return this:
```
├─┬ dep-2@2.0.0
│ └── UNMET DEPENDENCY gulp@^3.9.0

npm ERR! missing: gulp@^3.9.0, required by pkg-that-just-requires-gulp@1.0.0
```

However, this is what we **actually** see:

```
$ npm ls
├─┬ pkg-that-just-requires-gulp@1.0.0
│ └── UNMET DEPENDENCY gulp@^3.9.0
└──  extraneous error: ENOENT, open '/Users/aleksey/my-project/node_modules/vinyl-fs/package.json

npm ERR! extraneous: vinyl-fs /Users/aleksey/my-project/node_modules/vinyl-fs
npm ERR! error in /Users/aleksey/my-project//node_modules/vinyl-fs: ENOENT, open '/Users/aleksey/my-project/node_modules/vinyl-fs/package.json'
npm ERR! missing: gulp@^3.9.0, required by pkg-that-just-requires-gulp@1.0.0
```

Examining the tree reveals that an `vinyl-fs` directory, containing nothing but `node_modules` is retained in `node_modules` even if it's been uninstalled along with gulp:

```
1$ tree node_modules/vinyl-fs
node_modules/vinyl-fs
└── node_modules

1 directory, 0 files
```

That's what causes the erroneous `ENOENT` error and the extraneous message.

`npm install`ing gulp again, does not fix the modules tree.

### PR DESCRIPTION
**Pull request by chrisirhc**
Fixes #10887 #10938

I haven't added a test for the main modules' `node_module/.bin`, this removes `node_module/*/node_modules/.bin` so that empty modules can be removed.

### CODE REVIEW

**Comment by othiym23** [comment]
Hmm... we may want to hoist and name that error handler to a function declaration, and @iarna should review this because she's the expert on the installer, but this looks good to me aside from those concerns. Thanks for including a test!

**Comment by chrisirhc** [comment]
Sounds good. I attempted to use a function declaration and cleaned up the duplicate cb() call logic. I'll await more reviewing before I squash the changes.

**Comment by lxe** [comment]
:+1:

**Comment by iarna** [comment]
This was merged to 3.5.5! =)

**Comment by chrisirhc** [comment]
Hooray! :smile:

**Pull request closed without merging**
