### PR TITLE
Release 3.3.5 updates

### PR DESCRIPTION
**Pull request by iarna**
Module updates for 3.3.5

### CODE REVIEW

**Comment by iarna** [comment]
3.3.5 is released

**Comment by jrit** [comment]
I believe in the release notes where it says Windows users should `npm install -f -g npm` it should say `npm install -f -g npm@v3.3.5` or you may just end up with the same version that is already installed. This was my experience anyway.

**Comment by iarna** [comment]
Well, it would get you `npm@3.3.4` which is the current latest release. If you actually want the current testing release then yes, `npm@3.3.5` or `npm@next`.

**Comment by jrit** [comment]
Yeah, I should probably look at the tags on the releases :smile: - thanks

**Pull request closed without merging**
