### PR TITLE
chore: ignore .nyc_output

### PR DESCRIPTION
**Pull request by MylesBorins**
This will help avoid an accidental publish or commit filled with
code coverage data

Ref: https://github.com/npm/npm/issues/12873

### CODE REVIEW

**Comment by zkat** [comment]
haha. whoops. Thanks for this, Myles!

**Comment by TheAlphaNerd** [comment]
My pleasure!

**Comment by zkat** [comment]
This was included in `npm@3.9.5`, thanks a bunch, @TheAlphaNerd! 🎉 💃 

I'll close this once it's fixed on LTS as well, which should be whenever we cook up a release for that.

**Comment by zkat** [comment]
I've merged this into the LTS branch, and it'll be included whenever we actually release that. Thanks again! 🎉

**Pull request closed without merging**
