### PR TITLE
deps: upgrade node-gyp to v3.4.0 (lts)

### PR DESCRIPTION
**Pull request by rvagg**
Same as https://github.com/npm/npm/pull/13199 but for 2.x

### CODE REVIEW

**Comment by zkat** [comment]
(note: we might need to reinstall this cause there's missing deps, I think, but I'll still attribute it to you, Rod)

**Comment by zkat** [comment]
This was merged into LTS and will be released into our next LTS this week! Thanks,

**Comment by rvagg** [comment]
@zkat for future reference what should I be doing here? A complete `rm -rf node_modules` and reinstall? I just did `npm i node-gyp@latest -S` and I believe it was with npm@3. Perhaps an `npm dedupe` would have done the trick?

**Comment by zkat** [comment]
I'm not actually sure what the difference was? Our `.npmrc` should be taking care of those installed. Doing `rm -rf` on `node_modules/`, installing the way you did, and doing a `git add -A node_modules package.json` should generally be enough to get the commit right.

Also, this was included in `npm@2.15.9`. Thanks! I'm closing this for now, but feel free to keep talking in here.

**Pull request closed without merging**
