### PR TITLE
install: simplify fetchPackageMetadata

### PR DESCRIPTION
**Pull request by othiym23**
Make the logic a little more similar to what `addNamed` does in the cache, but mostly take advantage of `semver.maxSatisfying()`.

Needs tests.

Fixes: #10641 

**r**: @iarna

### CODE REVIEW

**Comment by iarna** [comment]
LGTM 🐑

**Comment by alubbe** [comment]
What's the status on this? It would be awesome to see #10641 fixed :)

**Comment by alubbe** [comment]
Sorry for pinging you again, any chance to see this merged soon?

**Comment by iarna** [comment]
@alubbe it needs tests, when it gets tests (from the cli team or others) we can land it. If you'd like to help, a PR against the `othiym23/max-satisfaxion` branch that adds tests would be super!

**Comment by iarna** [comment]
Closing as obsoleted by #15205

**Pull request closed without merging**
