### PR TITLE
Remove nock and get tests running green in 2.x

### PR DESCRIPTION
**Pull request by zkat**
This is a port of #10706 to the 2.x branch.

### CODE REVIEW

**Comment by zkat** [comment]
There's some git-related flakiness I'm gonna have to spend time on for this. :(

**Comment by zkat** [comment]
This is ready for review ^_^

**Comment by othiym23** [comment]
:sheep::ambulance::boom: 

It's worth calling out the bug fix implicit in the changed stream usage in `CHANGELOG.md` whenever this goes out. Copypasta @iarna's description of the problem / fix?

**Comment by iarna** [comment]
This was merged to 2.14.16! =)

**Pull request closed without merging**
