### PR TITLE
Passing args into run-scripts

### PR DESCRIPTION
**Pull request by bcoe**
this is the start of an approach for passing arguments into run-scripts that @isaacs and I have been talking about. It allows you to run:

`npm run-script start -- --foo=3`

The problem is that it breaks the ability to run a script in the context of a package, e.g., `npm start <package> <package> <package>`, `npm run-script start <package>`.

We will still have the ability to run commands in the context of another package, with with the syntax:

`npm explore <pkg> -- run test`, which seems like a reasonable compromise

thoughts

See #3494

### CODE REVIEW

**Comment by machineghost** [comment]
I just wanted to +1 (:+1: )  the evils of the extra `--`.  I lost about half an hour trying the natural/logical syntax (ie. `npm test --foo`), before finally giving up and Googling my way to this thread.

In general well-designed software strives to make its users refer to the manual as infrequently as possible. But with the current extra `--` syntax a user has to either:

* stumble on to this thread, or
* `npm help package.json`, then
  * `npm help scripts`, then
  * `npm help run-scripts`
  * (wasting the time to read through the non-helpful parts of those first two before you can even get to the third)

Removing the `--` requirement will make the tool much more friendly to non-Node-experts, by making `npm test --foo` "just work."  Kudos to anyone who can find the time to implement it.

**Comment by ashtonwar** [comment]
For anyone who doesn't like the extra `--` I wrote a [small utility](https://github.com/ashtonwar/npm-run-improved).

```sh
$ npmr command -vf # npm run command -- -vf
```

`npm install -g npm-run-improved`

**Comment by stefanmaric** [comment]
Maybe I'm a bit late.

> We are not going to support passing args into the middle of the script, sorry.

I was looking to create parameterized npm scripts that interpolate args in arbitrary places, not only at the end. I came to a quick&dirty solution that I haven't seen anywhere else so I'm posting it here for future readers.

You just need to wrap your script in an immediately invoked function:

```json
{
  "print": "f(){ echo Hello $1! && echo Bye $2! ;};f",
  "test": "npm run print -- world stranger"
}
```

You get:

```shell
$ npm test -s # -s is to suppress npm messages for this example
Hello world!
Bye stranger!
```

You can also use `$*` which refers to all arguments.

This of course won't work on Windows unless you're using the Windows Subsystem for Linux (WSL, aka Bash for Windows), but since it is portable `sh` it should work everywhere else.

I would use this for dead-simple scripts only. Otherwise, you're better set with a separated `node` or `sh` script file as @isaacs said.

**Comment by kolya-ay** [comment]
@stefanmaric, great hack! Exactly what I looked for, thank you

**Pull request merged**
