### PR TITLE
tar: warn when using Node 6+

### PR DESCRIPTION
**Pull request by othiym23**
This should only live until the team lands a durable fix to #5082.
- [x] Tweak the message to include "4.4" as well as "Node.js LTS".

**r**: @iarna 
**r**: @zkat 

(/cc @sindresorhus)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks good. Thanks for doing this :)

**Comment by iarna** [comment]
LGTM 🐑

**Comment by ChALkeR** [comment]
Hope this is not needed now =).

**Comment by Fishrock123** [comment]
Link for ^ https://github.com/npm/fstream/pull/53

**Comment by othiym23** [comment]
Shipped as part of `npm@2.15.7` and `npm@3.10.0`, but in turn reverted by 92e43444d9204f749f83512aeab5d5e0a2d085a7 / c189723110497a17dac3b0596f2916deeed93ee7 and superseded by 2c49265c6746d29ae0cd5f3532d28c5950f9847e / 8802f6c152ea35cb9e5269c077c3a2f9df411afc, which are included in `npm@2.15.8` / `npm@3.10.1`. :tada:

**Pull request closed without merging**
