### PR TITLE
Rewrite legacy tests

### PR DESCRIPTION
**Pull request by iarna**
The great legacy test rewrite. All of the things in `test/packages` have been mechanically converted into stand alone tap tests in `test/tap/legacy-*.js`. Remaining work to be done is:

Port tests to tap:

@zkat will do these:
- [x] test/tap/legacy-array-bin.js
- [x] test/tap/legacy-blerg.js
- [x] test/tap/legacy-blerg3.js
- [x] test/tap/legacy-dir-bin.js
- [x] test/tap/legacy-env-reader.js
- [x] test/tap/legacy-files.js
- [x] test/tap/legacy-ignore-nested-nm.js
- [x] test/tap/legacy-ignore.js

@iarna will do these:
- [x] test/tap/legacy-missing-bindir.js
  - [x] test/tap/legacy-no-auth-leak.js (new test)
- [x] test/tap/legacy-optional-deps.js
- [x] test/tap/legacy-platform-all.js
- [x] test/tap/legacy-platform.js
- [x] test/tap/legacy-private.js
- [x] test/tap/legacy-shrinkwrap.js
- [x] test/tap/legacy-test-package.js
- [x] test/tap/legacy-url-dep.js

See 4238ea9 for an example of what these ports look like.

When one of us is done with our list above we'll check back in and probably move on to the following two (or split up the remaining legacy tests above, depending on progress).

We also need to write tests that:
- [x] Ensure that the artifact created by `npm pack` is able to install itself.

### CODE REVIEW

**Comment by iarna** [comment]
@kat `blerg`, `blerg3` & `missing-bindir` all have asserts around not leaking auth info. I'm doing the last of those and I'll pull it out into its own tests, so feel free to ditch the first two.

**Comment by iarna** [comment]
:boom: :sheep:

**Comment by zkat** [comment]
This needs to be rebased on 2.x before merging it there, and it'll take a bit to make sure everything is passing properly over in LTS. I'll make a separate PR for that. :)

**Comment by zkat** [comment]
This was merged and included in `npm@3.7.4`.

**Pull request closed without merging**
