### PR TITLE
version: still create commit with --no-git-tag-version

### PR DESCRIPTION
**Pull request by josephfrazier**
This fixes https://github.com/npm/npm/issues/17327.

### CODE REVIEW

**Comment by josephfrazier** [comment]
Hmm, not sure what's going on with the Travis tests. I *was* reproducing some failures locally (Ubuntu 17.04, Node v8.1.3) when I imitated the Travis build by running:

```bash
node . rebuild --depth=0
node . install --ignore-scripts
node . prune
node --version
make -j4 doc
node . run tap -- "test/tap/*.js" "test/broken-under-nyc/*.js"
```

However, after changing the last line to run only the failing/pending tests on Travis (in https://github.com/npm/npm/pull/17586/commits/b6812fcca4d54a2d063b4acc9b2eaa251d650b63), the previously-failing tests pass locally, while the pending ones remain pending.

**Comment by josephfrazier** [comment]
I fixed the relevant tests in https://github.com/npm/npm/pull/17586/commits/ec5329ed4ff166173023dc2932e1068b1cf80629, but there's still one seemingly spurious failure: https://travis-ci.org/npm/npm/jobs/249762403#L551-L569

I haven't been able to replicate this one locally, even inside a Docker container built from the following Dockerfile (adapted from `.travis.yml`):

```docker
FROM node:8
RUN mkdir -p /var/run/couchdb
RUN git config --global user.email "you@example.com"
RUN git config --global user.name "Your Name"
COPY . /app/
WORKDIR /app
RUN node . rebuild --depth=0
RUN node . install --ignore-scripts
RUN node . prune
RUN make -j4 doc
ENTRYPOINT node . run tap -- test/tap/00-verify-ls-ok.js
```

**Comment by iarna** [comment]
Your test error was caused by a travis issue that's been resolved in `release-next`, so I think that all the technical bits are addressed. I'll get with @zkat today and see what she felt like needed discussion.

**Comment by iarna** [comment]
As written this breaks the existing use case for `git-tag-version` (which disables the commit and the tag) and folks rely on that, so we're not keen on changing it.

I think it's possible to get the behavior you want without patching npm:

1. Having `git-tag-version = false` in the project `.npmrc`.
2. Adding a `postversion` script that looks like: `git add package.json package-lock.json && git commit -mv$npm_package_version` or (on windows) git add package.json package-lock.json && git commit -mv%npm_package_version%`

Does that do what you were aiming for?

**Comment by josephfrazier** [comment]
> As written this breaks the existing use case for git-tag-version (which disables the commit and the tag) and folks rely on that, so we're not keen on changing it.

Good point. I had considered that, but decided to propose the change anyway to see how it was received. Thanks for confirming that the behavior shouldn't change.

> I think it's possible to get the behavior you want without patching npm:

Thanks for the suggestion! This seems to work ok, but it's a bit clunky, given the fact that the script is not cross-platform (though [cross-var](https://github.com/elijahmanor/cross-var) might help with this). What if we introduced a new option/flag called `git-commit-version` that defaults to the value of `git-tag-version`, but can be overridden by explicitly setting `git-commit-version = true` in `.npmrc`, or passing `--git-commit-version` on the CLI? This should preserve the current `--no-git-tag-version` behavior, while giving users the ability to automatically commit as well.

**Pull request closed without merging**
